// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gateway/v1/trip.proto

package gatewayv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchTripsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartDate    string                 `protobuf:"bytes,3,opt,name=depart_date,json=departDate,proto3" json:"depart_date,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTripsRequest) Reset() {
	*x = SearchTripsRequest{}
	mi := &file_gateway_v1_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTripsRequest) ProtoMessage() {}

func (x *SearchTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTripsRequest.ProtoReflect.Descriptor instead.
func (*SearchTripsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_trip_proto_rawDescGZIP(), []int{0}
}

func (x *SearchTripsRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SearchTripsRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SearchTripsRequest) GetDepartDate() string {
	if x != nil {
		return x.DepartDate
	}
	return ""
}

func (x *SearchTripsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchTripsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchTripsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTripsReply) Reset() {
	*x = SearchTripsReply{}
	mi := &file_gateway_v1_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTripsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTripsReply) ProtoMessage() {}

func (x *SearchTripsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTripsReply.ProtoReflect.Descriptor instead.
func (*SearchTripsReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_trip_proto_rawDescGZIP(), []int{1}
}

func (x *SearchTripsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTripDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripDetailRequest) Reset() {
	*x = GetTripDetailRequest{}
	mi := &file_gateway_v1_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripDetailRequest) ProtoMessage() {}

func (x *GetTripDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripDetailRequest.ProtoReflect.Descriptor instead.
func (*GetTripDetailRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_trip_proto_rawDescGZIP(), []int{2}
}

func (x *GetTripDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTripDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripDetailReply) Reset() {
	*x = GetTripDetailReply{}
	mi := &file_gateway_v1_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripDetailReply) ProtoMessage() {}

func (x *GetTripDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripDetailReply.ProtoReflect.Descriptor instead.
func (*GetTripDetailReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_trip_proto_rawDescGZIP(), []int{3}
}

type PublishTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartTime    string                 `protobuf:"bytes,3,opt,name=depart_time,json=departTime,proto3" json:"depart_time,omitempty"`
	ArriveTime    string                 `protobuf:"bytes,4,opt,name=arrive_time,json=arriveTime,proto3" json:"arrive_time,omitempty"`
	SeatsTotal    int32                  `protobuf:"varint,5,opt,name=seats_total,json=seatsTotal,proto3" json:"seats_total,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTripRequest) Reset() {
	*x = PublishTripRequest{}
	mi := &file_gateway_v1_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTripRequest) ProtoMessage() {}

func (x *PublishTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTripRequest.ProtoReflect.Descriptor instead.
func (*PublishTripRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_trip_proto_rawDescGZIP(), []int{4}
}

func (x *PublishTripRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *PublishTripRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PublishTripRequest) GetDepartTime() string {
	if x != nil {
		return x.DepartTime
	}
	return ""
}

func (x *PublishTripRequest) GetArriveTime() string {
	if x != nil {
		return x.ArriveTime
	}
	return ""
}

func (x *PublishTripRequest) GetSeatsTotal() int32 {
	if x != nil {
		return x.SeatsTotal
	}
	return 0
}

func (x *PublishTripRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PublishTripReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        int64                  `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTripReply) Reset() {
	*x = PublishTripReply{}
	mi := &file_gateway_v1_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTripReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTripReply) ProtoMessage() {}

func (x *PublishTripReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTripReply.ProtoReflect.Descriptor instead.
func (*PublishTripReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_trip_proto_rawDescGZIP(), []int{5}
}

func (x *PublishTripReply) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

var File_gateway_v1_trip_proto protoreflect.FileDescriptor

const file_gateway_v1_trip_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/v1/trip.proto\x12\n" +
	"gateway.v1\x1a\x1cgoogle/api/annotations.proto\"\xa0\x01\n" +
	"\x12SearchTripsRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdepart_date\x18\x03 \x01(\tR\n" +
	"departDate\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"(\n" +
	"\x10SearchTripsReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"&\n" +
	"\x14GetTripDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12GetTripDetailReply\"\xc7\x01\n" +
	"\x12PublishTripRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdepart_time\x18\x03 \x01(\tR\n" +
	"departTime\x12\x1f\n" +
	"\varrive_time\x18\x04 \x01(\tR\n" +
	"arriveTime\x12\x1f\n" +
	"\vseats_total\x18\x05 \x01(\x05R\n" +
	"seatsTotal\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\"+\n" +
	"\x10PublishTripReply\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\x03R\x06tripId2\xd1\x02\n" +
	"\x12GatewayTripService\x12c\n" +
	"\vSearchTrips\x12\x1e.gateway.v1.SearchTripsRequest\x1a\x1c.gateway.v1.SearchTripsReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/carpool/trips\x12n\n" +
	"\rGetTripDetail\x12 .gateway.v1.GetTripDetailRequest\x1a\x1e.gateway.v1.GetTripDetailReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/carpool/trips/{id}\x12f\n" +
	"\vPublishTrip\x12\x1e.gateway.v1.PublishTripRequest\x1a\x1c.gateway.v1.PublishTripReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/carpool/tripsB@Z>ride-hailing/services/gateway-service/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_trip_proto_rawDescOnce sync.Once
	file_gateway_v1_trip_proto_rawDescData []byte
)

func file_gateway_v1_trip_proto_rawDescGZIP() []byte {
	file_gateway_v1_trip_proto_rawDescOnce.Do(func() {
		file_gateway_v1_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_trip_proto_rawDesc), len(file_gateway_v1_trip_proto_rawDesc)))
	})
	return file_gateway_v1_trip_proto_rawDescData
}

var file_gateway_v1_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gateway_v1_trip_proto_goTypes = []any{
	(*SearchTripsRequest)(nil),   // 0: gateway.v1.SearchTripsRequest
	(*SearchTripsReply)(nil),     // 1: gateway.v1.SearchTripsReply
	(*GetTripDetailRequest)(nil), // 2: gateway.v1.GetTripDetailRequest
	(*GetTripDetailReply)(nil),   // 3: gateway.v1.GetTripDetailReply
	(*PublishTripRequest)(nil),   // 4: gateway.v1.PublishTripRequest
	(*PublishTripReply)(nil),     // 5: gateway.v1.PublishTripReply
}
var file_gateway_v1_trip_proto_depIdxs = []int32{
	0, // 0: gateway.v1.GatewayTripService.SearchTrips:input_type -> gateway.v1.SearchTripsRequest
	2, // 1: gateway.v1.GatewayTripService.GetTripDetail:input_type -> gateway.v1.GetTripDetailRequest
	4, // 2: gateway.v1.GatewayTripService.PublishTrip:input_type -> gateway.v1.PublishTripRequest
	1, // 3: gateway.v1.GatewayTripService.SearchTrips:output_type -> gateway.v1.SearchTripsReply
	3, // 4: gateway.v1.GatewayTripService.GetTripDetail:output_type -> gateway.v1.GetTripDetailReply
	5, // 5: gateway.v1.GatewayTripService.PublishTrip:output_type -> gateway.v1.PublishTripReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_v1_trip_proto_init() }
func file_gateway_v1_trip_proto_init() {
	if File_gateway_v1_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_trip_proto_rawDesc), len(file_gateway_v1_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_trip_proto_goTypes,
		DependencyIndexes: file_gateway_v1_trip_proto_depIdxs,
		MessageInfos:      file_gateway_v1_trip_proto_msgTypes,
	}.Build()
	File_gateway_v1_trip_proto = out.File
	file_gateway_v1_trip_proto_goTypes = nil
	file_gateway_v1_trip_proto_depIdxs = nil
}
