// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: passenger/v1/passenger.proto

package passengerv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPassengerServiceEnsurePassenger = "/passenger.v1.PassengerService/EnsurePassenger"
const OperationPassengerServiceGetPassenger = "/passenger.v1.PassengerService/GetPassenger"
const OperationPassengerServiceUpdatePassenger = "/passenger.v1.PassengerService/UpdatePassenger"

type PassengerServiceHTTPServer interface {
	EnsurePassenger(context.Context, *EnsurePassengerRequest) (*PassengerProfileReply, error)
	GetPassenger(context.Context, *GetPassengerRequest) (*PassengerProfileReply, error)
	UpdatePassenger(context.Context, *UpdatePassengerRequest) (*PassengerProfileReply, error)
}

func RegisterPassengerServiceHTTPServer(s *http.Server, srv PassengerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/passengers/ensure", _PassengerService_EnsurePassenger0_HTTP_Handler(srv))
	r.GET("/v1/passengers/{id}", _PassengerService_GetPassenger0_HTTP_Handler(srv))
	r.PUT("/v1/passengers/{id}", _PassengerService_UpdatePassenger0_HTTP_Handler(srv))
}

func _PassengerService_EnsurePassenger0_HTTP_Handler(srv PassengerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnsurePassengerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassengerServiceEnsurePassenger)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnsurePassenger(ctx, req.(*EnsurePassengerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PassengerProfileReply)
		return ctx.Result(200, reply)
	}
}

func _PassengerService_GetPassenger0_HTTP_Handler(srv PassengerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPassengerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassengerServiceGetPassenger)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPassenger(ctx, req.(*GetPassengerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PassengerProfileReply)
		return ctx.Result(200, reply)
	}
}

func _PassengerService_UpdatePassenger0_HTTP_Handler(srv PassengerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePassengerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassengerServiceUpdatePassenger)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePassenger(ctx, req.(*UpdatePassengerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PassengerProfileReply)
		return ctx.Result(200, reply)
	}
}

type PassengerServiceHTTPClient interface {
	EnsurePassenger(ctx context.Context, req *EnsurePassengerRequest, opts ...http.CallOption) (rsp *PassengerProfileReply, err error)
	GetPassenger(ctx context.Context, req *GetPassengerRequest, opts ...http.CallOption) (rsp *PassengerProfileReply, err error)
	UpdatePassenger(ctx context.Context, req *UpdatePassengerRequest, opts ...http.CallOption) (rsp *PassengerProfileReply, err error)
}

type PassengerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPassengerServiceHTTPClient(client *http.Client) PassengerServiceHTTPClient {
	return &PassengerServiceHTTPClientImpl{client}
}

func (c *PassengerServiceHTTPClientImpl) EnsurePassenger(ctx context.Context, in *EnsurePassengerRequest, opts ...http.CallOption) (*PassengerProfileReply, error) {
	var out PassengerProfileReply
	pattern := "/v1/passengers/ensure"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassengerServiceEnsurePassenger))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PassengerServiceHTTPClientImpl) GetPassenger(ctx context.Context, in *GetPassengerRequest, opts ...http.CallOption) (*PassengerProfileReply, error) {
	var out PassengerProfileReply
	pattern := "/v1/passengers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPassengerServiceGetPassenger))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PassengerServiceHTTPClientImpl) UpdatePassenger(ctx context.Context, in *UpdatePassengerRequest, opts ...http.CallOption) (*PassengerProfileReply, error) {
	var out PassengerProfileReply
	pattern := "/v1/passengers/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassengerServiceUpdatePassenger))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
