// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: passenger/v1/passenger.proto

package passengerv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsurePassengerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsurePassengerRequest) Reset() {
	*x = EnsurePassengerRequest{}
	mi := &file_passenger_v1_passenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsurePassengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsurePassengerRequest) ProtoMessage() {}

func (x *EnsurePassengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_v1_passenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsurePassengerRequest.ProtoReflect.Descriptor instead.
func (*EnsurePassengerRequest) Descriptor() ([]byte, []int) {
	return file_passenger_v1_passenger_proto_rawDescGZIP(), []int{0}
}

func (x *EnsurePassengerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnsurePassengerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetPassengerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassengerRequest) Reset() {
	*x = GetPassengerRequest{}
	mi := &file_passenger_v1_passenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassengerRequest) ProtoMessage() {}

func (x *GetPassengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_v1_passenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassengerRequest.ProtoReflect.Descriptor instead.
func (*GetPassengerRequest) Descriptor() ([]byte, []int) {
	return file_passenger_v1_passenger_proto_rawDescGZIP(), []int{1}
}

func (x *GetPassengerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdatePassengerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname          string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone             string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl         string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CommonAddress     string                 `protobuf:"bytes,5,opt,name=common_address,json=commonAddress,proto3" json:"common_address,omitempty"`
	PaymentPreference string                 `protobuf:"bytes,6,opt,name=payment_preference,json=paymentPreference,proto3" json:"payment_preference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePassengerRequest) Reset() {
	*x = UpdatePassengerRequest{}
	mi := &file_passenger_v1_passenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePassengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePassengerRequest) ProtoMessage() {}

func (x *UpdatePassengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_v1_passenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePassengerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePassengerRequest) Descriptor() ([]byte, []int) {
	return file_passenger_v1_passenger_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePassengerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePassengerRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdatePassengerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdatePassengerRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdatePassengerRequest) GetCommonAddress() string {
	if x != nil {
		return x.CommonAddress
	}
	return ""
}

func (x *UpdatePassengerRequest) GetPaymentPreference() string {
	if x != nil {
		return x.PaymentPreference
	}
	return ""
}

type PassengerProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname          string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone             string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl         string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CommonAddress     string                 `protobuf:"bytes,5,opt,name=common_address,json=commonAddress,proto3" json:"common_address,omitempty"`
	PaymentPreference string                 `protobuf:"bytes,6,opt,name=payment_preference,json=paymentPreference,proto3" json:"payment_preference,omitempty"`
	Status            int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PassengerProfile) Reset() {
	*x = PassengerProfile{}
	mi := &file_passenger_v1_passenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerProfile) ProtoMessage() {}

func (x *PassengerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_v1_passenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerProfile.ProtoReflect.Descriptor instead.
func (*PassengerProfile) Descriptor() ([]byte, []int) {
	return file_passenger_v1_passenger_proto_rawDescGZIP(), []int{3}
}

func (x *PassengerProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PassengerProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PassengerProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PassengerProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PassengerProfile) GetCommonAddress() string {
	if x != nil {
		return x.CommonAddress
	}
	return ""
}

func (x *PassengerProfile) GetPaymentPreference() string {
	if x != nil {
		return x.PaymentPreference
	}
	return ""
}

func (x *PassengerProfile) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PassengerProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PassengerProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type PassengerProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passenger     *PassengerProfile      `protobuf:"bytes,1,opt,name=passenger,proto3" json:"passenger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassengerProfileReply) Reset() {
	*x = PassengerProfileReply{}
	mi := &file_passenger_v1_passenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerProfileReply) ProtoMessage() {}

func (x *PassengerProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_v1_passenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerProfileReply.ProtoReflect.Descriptor instead.
func (*PassengerProfileReply) Descriptor() ([]byte, []int) {
	return file_passenger_v1_passenger_proto_rawDescGZIP(), []int{4}
}

func (x *PassengerProfileReply) GetPassenger() *PassengerProfile {
	if x != nil {
		return x.Passenger
	}
	return nil
}

var File_passenger_v1_passenger_proto protoreflect.FileDescriptor

const file_passenger_v1_passenger_proto_rawDesc = "" +
	"\n" +
	"\x1cpassenger/v1/passenger.proto\x12\fpassenger.v1\x1a\x1cgoogle/api/annotations.proto\">\n" +
	"\x16EnsurePassengerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"%\n" +
	"\x13GetPassengerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xcf\x01\n" +
	"\x16UpdatePassengerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12%\n" +
	"\x0ecommon_address\x18\x05 \x01(\tR\rcommonAddress\x12-\n" +
	"\x12payment_preference\x18\x06 \x01(\tR\x11paymentPreference\"\x9f\x02\n" +
	"\x10PassengerProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12%\n" +
	"\x0ecommon_address\x18\x05 \x01(\tR\rcommonAddress\x12-\n" +
	"\x12payment_preference\x18\x06 \x01(\tR\x11paymentPreference\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"U\n" +
	"\x15PassengerProfileReply\x12<\n" +
	"\tpassenger\x18\x01 \x01(\v2\x1e.passenger.v1.PassengerProfileR\tpassenger2\x85\x03\n" +
	"\x10PassengerService\x12~\n" +
	"\x0fEnsurePassenger\x12$.passenger.v1.EnsurePassengerRequest\x1a#.passenger.v1.PassengerProfileReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/passengers/ensure\x12s\n" +
	"\fGetPassenger\x12!.passenger.v1.GetPassengerRequest\x1a#.passenger.v1.PassengerProfileReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/passengers/{id}\x12|\n" +
	"\x0fUpdatePassenger\x12$.passenger.v1.UpdatePassengerRequest\x1a#.passenger.v1.PassengerProfileReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/passengers/{id}BFZDride-hailing/services/passenger-service/api/passenger/v1;passengerv1b\x06proto3"

var (
	file_passenger_v1_passenger_proto_rawDescOnce sync.Once
	file_passenger_v1_passenger_proto_rawDescData []byte
)

func file_passenger_v1_passenger_proto_rawDescGZIP() []byte {
	file_passenger_v1_passenger_proto_rawDescOnce.Do(func() {
		file_passenger_v1_passenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_passenger_v1_passenger_proto_rawDesc), len(file_passenger_v1_passenger_proto_rawDesc)))
	})
	return file_passenger_v1_passenger_proto_rawDescData
}

var file_passenger_v1_passenger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_passenger_v1_passenger_proto_goTypes = []any{
	(*EnsurePassengerRequest)(nil), // 0: passenger.v1.EnsurePassengerRequest
	(*GetPassengerRequest)(nil),    // 1: passenger.v1.GetPassengerRequest
	(*UpdatePassengerRequest)(nil), // 2: passenger.v1.UpdatePassengerRequest
	(*PassengerProfile)(nil),       // 3: passenger.v1.PassengerProfile
	(*PassengerProfileReply)(nil),  // 4: passenger.v1.PassengerProfileReply
}
var file_passenger_v1_passenger_proto_depIdxs = []int32{
	3, // 0: passenger.v1.PassengerProfileReply.passenger:type_name -> passenger.v1.PassengerProfile
	0, // 1: passenger.v1.PassengerService.EnsurePassenger:input_type -> passenger.v1.EnsurePassengerRequest
	1, // 2: passenger.v1.PassengerService.GetPassenger:input_type -> passenger.v1.GetPassengerRequest
	2, // 3: passenger.v1.PassengerService.UpdatePassenger:input_type -> passenger.v1.UpdatePassengerRequest
	4, // 4: passenger.v1.PassengerService.EnsurePassenger:output_type -> passenger.v1.PassengerProfileReply
	4, // 5: passenger.v1.PassengerService.GetPassenger:output_type -> passenger.v1.PassengerProfileReply
	4, // 6: passenger.v1.PassengerService.UpdatePassenger:output_type -> passenger.v1.PassengerProfileReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_passenger_v1_passenger_proto_init() }
func file_passenger_v1_passenger_proto_init() {
	if File_passenger_v1_passenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_passenger_v1_passenger_proto_rawDesc), len(file_passenger_v1_passenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_passenger_v1_passenger_proto_goTypes,
		DependencyIndexes: file_passenger_v1_passenger_proto_depIdxs,
		MessageInfos:      file_passenger_v1_passenger_proto_msgTypes,
	}.Build()
	File_passenger_v1_passenger_proto = out.File
	file_passenger_v1_passenger_proto_goTypes = nil
	file_passenger_v1_passenger_proto_depIdxs = nil
}
