// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: passenger/v1/passenger.proto

package passengerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PassengerService_EnsurePassenger_FullMethodName = "/passenger.v1.PassengerService/EnsurePassenger"
	PassengerService_GetPassenger_FullMethodName    = "/passenger.v1.PassengerService/GetPassenger"
	PassengerService_UpdatePassenger_FullMethodName = "/passenger.v1.PassengerService/UpdatePassenger"
)

// PassengerServiceClient is the client API for PassengerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PassengerServiceClient interface {
	EnsurePassenger(ctx context.Context, in *EnsurePassengerRequest, opts ...grpc.CallOption) (*PassengerProfileReply, error)
	GetPassenger(ctx context.Context, in *GetPassengerRequest, opts ...grpc.CallOption) (*PassengerProfileReply, error)
	UpdatePassenger(ctx context.Context, in *UpdatePassengerRequest, opts ...grpc.CallOption) (*PassengerProfileReply, error)
}

type passengerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassengerServiceClient(cc grpc.ClientConnInterface) PassengerServiceClient {
	return &passengerServiceClient{cc}
}

func (c *passengerServiceClient) EnsurePassenger(ctx context.Context, in *EnsurePassengerRequest, opts ...grpc.CallOption) (*PassengerProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PassengerProfileReply)
	err := c.cc.Invoke(ctx, PassengerService_EnsurePassenger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) GetPassenger(ctx context.Context, in *GetPassengerRequest, opts ...grpc.CallOption) (*PassengerProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PassengerProfileReply)
	err := c.cc.Invoke(ctx, PassengerService_GetPassenger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) UpdatePassenger(ctx context.Context, in *UpdatePassengerRequest, opts ...grpc.CallOption) (*PassengerProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PassengerProfileReply)
	err := c.cc.Invoke(ctx, PassengerService_UpdatePassenger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerServiceServer is the server API for PassengerService service.
// All implementations must embed UnimplementedPassengerServiceServer
// for forward compatibility.
type PassengerServiceServer interface {
	EnsurePassenger(context.Context, *EnsurePassengerRequest) (*PassengerProfileReply, error)
	GetPassenger(context.Context, *GetPassengerRequest) (*PassengerProfileReply, error)
	UpdatePassenger(context.Context, *UpdatePassengerRequest) (*PassengerProfileReply, error)
	mustEmbedUnimplementedPassengerServiceServer()
}

// UnimplementedPassengerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPassengerServiceServer struct{}

func (UnimplementedPassengerServiceServer) EnsurePassenger(context.Context, *EnsurePassengerRequest) (*PassengerProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsurePassenger not implemented")
}
func (UnimplementedPassengerServiceServer) GetPassenger(context.Context, *GetPassengerRequest) (*PassengerProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPassenger not implemented")
}
func (UnimplementedPassengerServiceServer) UpdatePassenger(context.Context, *UpdatePassengerRequest) (*PassengerProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePassenger not implemented")
}
func (UnimplementedPassengerServiceServer) mustEmbedUnimplementedPassengerServiceServer() {}
func (UnimplementedPassengerServiceServer) testEmbeddedByValue()                          {}

// UnsafePassengerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PassengerServiceServer will
// result in compilation errors.
type UnsafePassengerServiceServer interface {
	mustEmbedUnimplementedPassengerServiceServer()
}

func RegisterPassengerServiceServer(s grpc.ServiceRegistrar, srv PassengerServiceServer) {
	// If the following call panics, it indicates UnimplementedPassengerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PassengerService_ServiceDesc, srv)
}

func _PassengerService_EnsurePassenger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsurePassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).EnsurePassenger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_EnsurePassenger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).EnsurePassenger(ctx, req.(*EnsurePassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_GetPassenger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).GetPassenger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_GetPassenger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).GetPassenger(ctx, req.(*GetPassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_UpdatePassenger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePassengerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).UpdatePassenger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_UpdatePassenger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).UpdatePassenger(ctx, req.(*UpdatePassengerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PassengerService_ServiceDesc is the grpc.ServiceDesc for PassengerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PassengerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "passenger.v1.PassengerService",
	HandlerType: (*PassengerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsurePassenger",
			Handler:    _PassengerService_EnsurePassenger_Handler,
		},
		{
			MethodName: "GetPassenger",
			Handler:    _PassengerService_GetPassenger_Handler,
		},
		{
			MethodName: "UpdatePassenger",
			Handler:    _PassengerService_UpdatePassenger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passenger/v1/passenger.proto",
}
