// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: trip/v1/trip.proto

package tripv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TripService_SearchTrips_FullMethodName      = "/trip.v1.TripService/SearchTrips"
	TripService_GetTripDetail_FullMethodName    = "/trip.v1.TripService/GetTripDetail"
	TripService_PublishTrip_FullMethodName      = "/trip.v1.TripService/PublishTrip"
	TripService_ValidateLocation_FullMethodName = "/trip.v1.TripService/ValidateLocation"
	TripService_PreviewTripPrice_FullMethodName = "/trip.v1.TripService/PreviewTripPrice"
	TripService_SuggestLocations_FullMethodName = "/trip.v1.TripService/SuggestLocations"
	TripService_ListDriverTrips_FullMethodName  = "/trip.v1.TripService/ListDriverTrips"
	TripService_UpdateTripStatus_FullMethodName = "/trip.v1.TripService/UpdateTripStatus"
	TripService_ListCoupons_FullMethodName      = "/trip.v1.TripService/ListCoupons"
	TripService_ClaimCoupon_FullMethodName      = "/trip.v1.TripService/ClaimCoupon"
	TripService_PublishDemand_FullMethodName    = "/trip.v1.TripService/PublishDemand"
	TripService_ListMyDemands_FullMethodName    = "/trip.v1.TripService/ListMyDemands"
	TripService_CancelDemand_FullMethodName     = "/trip.v1.TripService/CancelDemand"
	TripService_DeleteTrip_FullMethodName       = "/trip.v1.TripService/DeleteTrip"
)

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	SearchTrips(ctx context.Context, in *SearchTripsRequest, opts ...grpc.CallOption) (*SearchTripsReply, error)
	GetTripDetail(ctx context.Context, in *GetTripDetailRequest, opts ...grpc.CallOption) (*GetTripDetailReply, error)
	PublishTrip(ctx context.Context, in *PublishTripRequest, opts ...grpc.CallOption) (*PublishTripReply, error)
	ValidateLocation(ctx context.Context, in *ValidateLocationRequest, opts ...grpc.CallOption) (*ValidateLocationReply, error)
	PreviewTripPrice(ctx context.Context, in *PreviewTripPriceRequest, opts ...grpc.CallOption) (*PreviewTripPriceReply, error)
	SuggestLocations(ctx context.Context, in *SuggestLocationsRequest, opts ...grpc.CallOption) (*SuggestLocationsReply, error)
	ListDriverTrips(ctx context.Context, in *ListDriverTripsRequest, opts ...grpc.CallOption) (*ListDriverTripsReply, error)
	UpdateTripStatus(ctx context.Context, in *UpdateTripStatusRequest, opts ...grpc.CallOption) (*UpdateTripStatusReply, error)
	ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsReply, error)
	ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponReply, error)
	PublishDemand(ctx context.Context, in *PublishDemandRequest, opts ...grpc.CallOption) (*PublishDemandReply, error)
	ListMyDemands(ctx context.Context, in *ListMyDemandsRequest, opts ...grpc.CallOption) (*ListMyDemandsReply, error)
	CancelDemand(ctx context.Context, in *CancelDemandRequest, opts ...grpc.CallOption) (*CancelDemandReply, error)
	DeleteTrip(ctx context.Context, in *DeleteTripRequest, opts ...grpc.CallOption) (*DeleteTripReply, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) SearchTrips(ctx context.Context, in *SearchTripsRequest, opts ...grpc.CallOption) (*SearchTripsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTripsReply)
	err := c.cc.Invoke(ctx, TripService_SearchTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripDetail(ctx context.Context, in *GetTripDetailRequest, opts ...grpc.CallOption) (*GetTripDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripDetailReply)
	err := c.cc.Invoke(ctx, TripService_GetTripDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) PublishTrip(ctx context.Context, in *PublishTripRequest, opts ...grpc.CallOption) (*PublishTripReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishTripReply)
	err := c.cc.Invoke(ctx, TripService_PublishTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ValidateLocation(ctx context.Context, in *ValidateLocationRequest, opts ...grpc.CallOption) (*ValidateLocationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateLocationReply)
	err := c.cc.Invoke(ctx, TripService_ValidateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) PreviewTripPrice(ctx context.Context, in *PreviewTripPriceRequest, opts ...grpc.CallOption) (*PreviewTripPriceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewTripPriceReply)
	err := c.cc.Invoke(ctx, TripService_PreviewTripPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) SuggestLocations(ctx context.Context, in *SuggestLocationsRequest, opts ...grpc.CallOption) (*SuggestLocationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestLocationsReply)
	err := c.cc.Invoke(ctx, TripService_SuggestLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListDriverTrips(ctx context.Context, in *ListDriverTripsRequest, opts ...grpc.CallOption) (*ListDriverTripsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriverTripsReply)
	err := c.cc.Invoke(ctx, TripService_ListDriverTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) UpdateTripStatus(ctx context.Context, in *UpdateTripStatusRequest, opts ...grpc.CallOption) (*UpdateTripStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTripStatusReply)
	err := c.cc.Invoke(ctx, TripService_UpdateTripStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponsReply)
	err := c.cc.Invoke(ctx, TripService_ListCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimCouponReply)
	err := c.cc.Invoke(ctx, TripService_ClaimCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) PublishDemand(ctx context.Context, in *PublishDemandRequest, opts ...grpc.CallOption) (*PublishDemandReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishDemandReply)
	err := c.cc.Invoke(ctx, TripService_PublishDemand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListMyDemands(ctx context.Context, in *ListMyDemandsRequest, opts ...grpc.CallOption) (*ListMyDemandsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyDemandsReply)
	err := c.cc.Invoke(ctx, TripService_ListMyDemands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelDemand(ctx context.Context, in *CancelDemandRequest, opts ...grpc.CallOption) (*CancelDemandReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelDemandReply)
	err := c.cc.Invoke(ctx, TripService_CancelDemand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) DeleteTrip(ctx context.Context, in *DeleteTripRequest, opts ...grpc.CallOption) (*DeleteTripReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTripReply)
	err := c.cc.Invoke(ctx, TripService_DeleteTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility.
type TripServiceServer interface {
	SearchTrips(context.Context, *SearchTripsRequest) (*SearchTripsReply, error)
	GetTripDetail(context.Context, *GetTripDetailRequest) (*GetTripDetailReply, error)
	PublishTrip(context.Context, *PublishTripRequest) (*PublishTripReply, error)
	ValidateLocation(context.Context, *ValidateLocationRequest) (*ValidateLocationReply, error)
	PreviewTripPrice(context.Context, *PreviewTripPriceRequest) (*PreviewTripPriceReply, error)
	SuggestLocations(context.Context, *SuggestLocationsRequest) (*SuggestLocationsReply, error)
	ListDriverTrips(context.Context, *ListDriverTripsRequest) (*ListDriverTripsReply, error)
	UpdateTripStatus(context.Context, *UpdateTripStatusRequest) (*UpdateTripStatusReply, error)
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error)
	ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponReply, error)
	PublishDemand(context.Context, *PublishDemandRequest) (*PublishDemandReply, error)
	ListMyDemands(context.Context, *ListMyDemandsRequest) (*ListMyDemandsReply, error)
	CancelDemand(context.Context, *CancelDemandRequest) (*CancelDemandReply, error)
	DeleteTrip(context.Context, *DeleteTripRequest) (*DeleteTripReply, error)
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTripServiceServer struct{}

func (UnimplementedTripServiceServer) SearchTrips(context.Context, *SearchTripsRequest) (*SearchTripsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTrips not implemented")
}
func (UnimplementedTripServiceServer) GetTripDetail(context.Context, *GetTripDetailRequest) (*GetTripDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripDetail not implemented")
}
func (UnimplementedTripServiceServer) PublishTrip(context.Context, *PublishTripRequest) (*PublishTripReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTrip not implemented")
}
func (UnimplementedTripServiceServer) ValidateLocation(context.Context, *ValidateLocationRequest) (*ValidateLocationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateLocation not implemented")
}
func (UnimplementedTripServiceServer) PreviewTripPrice(context.Context, *PreviewTripPriceRequest) (*PreviewTripPriceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewTripPrice not implemented")
}
func (UnimplementedTripServiceServer) SuggestLocations(context.Context, *SuggestLocationsRequest) (*SuggestLocationsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestLocations not implemented")
}
func (UnimplementedTripServiceServer) ListDriverTrips(context.Context, *ListDriverTripsRequest) (*ListDriverTripsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriverTrips not implemented")
}
func (UnimplementedTripServiceServer) UpdateTripStatus(context.Context, *UpdateTripStatusRequest) (*UpdateTripStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTripStatus not implemented")
}
func (UnimplementedTripServiceServer) ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCoupons not implemented")
}
func (UnimplementedTripServiceServer) ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimCoupon not implemented")
}
func (UnimplementedTripServiceServer) PublishDemand(context.Context, *PublishDemandRequest) (*PublishDemandReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishDemand not implemented")
}
func (UnimplementedTripServiceServer) ListMyDemands(context.Context, *ListMyDemandsRequest) (*ListMyDemandsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyDemands not implemented")
}
func (UnimplementedTripServiceServer) CancelDemand(context.Context, *CancelDemandRequest) (*CancelDemandReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelDemand not implemented")
}
func (UnimplementedTripServiceServer) DeleteTrip(context.Context, *DeleteTripRequest) (*DeleteTripReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTrip not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}
func (UnimplementedTripServiceServer) testEmbeddedByValue()                     {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	// If the following call panics, it indicates UnimplementedTripServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_SearchTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).SearchTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_SearchTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).SearchTrips(ctx, req.(*SearchTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripDetail(ctx, req.(*GetTripDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_PublishTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).PublishTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_PublishTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).PublishTrip(ctx, req.(*PublishTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ValidateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ValidateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ValidateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ValidateLocation(ctx, req.(*ValidateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_PreviewTripPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewTripPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).PreviewTripPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_PreviewTripPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).PreviewTripPrice(ctx, req.(*PreviewTripPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_SuggestLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).SuggestLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_SuggestLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).SuggestLocations(ctx, req.(*SuggestLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListDriverTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriverTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListDriverTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListDriverTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListDriverTrips(ctx, req.(*ListDriverTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_UpdateTripStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).UpdateTripStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_UpdateTripStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).UpdateTripStatus(ctx, req.(*UpdateTripStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListCoupons(ctx, req.(*ListCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ClaimCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ClaimCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ClaimCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ClaimCoupon(ctx, req.(*ClaimCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_PublishDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishDemandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).PublishDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_PublishDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).PublishDemand(ctx, req.(*PublishDemandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListMyDemands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyDemandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListMyDemands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListMyDemands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListMyDemands(ctx, req.(*ListMyDemandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelDemandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelDemand(ctx, req.(*CancelDemandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_DeleteTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).DeleteTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_DeleteTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).DeleteTrip(ctx, req.(*DeleteTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.v1.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTrips",
			Handler:    _TripService_SearchTrips_Handler,
		},
		{
			MethodName: "GetTripDetail",
			Handler:    _TripService_GetTripDetail_Handler,
		},
		{
			MethodName: "PublishTrip",
			Handler:    _TripService_PublishTrip_Handler,
		},
		{
			MethodName: "ValidateLocation",
			Handler:    _TripService_ValidateLocation_Handler,
		},
		{
			MethodName: "PreviewTripPrice",
			Handler:    _TripService_PreviewTripPrice_Handler,
		},
		{
			MethodName: "SuggestLocations",
			Handler:    _TripService_SuggestLocations_Handler,
		},
		{
			MethodName: "ListDriverTrips",
			Handler:    _TripService_ListDriverTrips_Handler,
		},
		{
			MethodName: "UpdateTripStatus",
			Handler:    _TripService_UpdateTripStatus_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _TripService_ListCoupons_Handler,
		},
		{
			MethodName: "ClaimCoupon",
			Handler:    _TripService_ClaimCoupon_Handler,
		},
		{
			MethodName: "PublishDemand",
			Handler:    _TripService_PublishDemand_Handler,
		},
		{
			MethodName: "ListMyDemands",
			Handler:    _TripService_ListMyDemands_Handler,
		},
		{
			MethodName: "CancelDemand",
			Handler:    _TripService_CancelDemand_Handler,
		},
		{
			MethodName: "DeleteTrip",
			Handler:    _TripService_DeleteTrip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip/v1/trip.proto",
}
