// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: trip/v1/trip.proto

package tripv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTripServiceCancelDemand = "/trip.v1.TripService/CancelDemand"
const OperationTripServiceClaimCoupon = "/trip.v1.TripService/ClaimCoupon"
const OperationTripServiceDeleteTrip = "/trip.v1.TripService/DeleteTrip"
const OperationTripServiceGetTripDetail = "/trip.v1.TripService/GetTripDetail"
const OperationTripServiceListCoupons = "/trip.v1.TripService/ListCoupons"
const OperationTripServiceListDriverTrips = "/trip.v1.TripService/ListDriverTrips"
const OperationTripServiceListMyDemands = "/trip.v1.TripService/ListMyDemands"
const OperationTripServicePreviewTripPrice = "/trip.v1.TripService/PreviewTripPrice"
const OperationTripServicePublishDemand = "/trip.v1.TripService/PublishDemand"
const OperationTripServicePublishTrip = "/trip.v1.TripService/PublishTrip"
const OperationTripServiceSearchTrips = "/trip.v1.TripService/SearchTrips"
const OperationTripServiceSuggestLocations = "/trip.v1.TripService/SuggestLocations"
const OperationTripServiceUpdateTripStatus = "/trip.v1.TripService/UpdateTripStatus"
const OperationTripServiceValidateLocation = "/trip.v1.TripService/ValidateLocation"

type TripServiceHTTPServer interface {
	CancelDemand(context.Context, *CancelDemandRequest) (*CancelDemandReply, error)
	ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponReply, error)
	DeleteTrip(context.Context, *DeleteTripRequest) (*DeleteTripReply, error)
	GetTripDetail(context.Context, *GetTripDetailRequest) (*GetTripDetailReply, error)
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error)
	ListDriverTrips(context.Context, *ListDriverTripsRequest) (*ListDriverTripsReply, error)
	ListMyDemands(context.Context, *ListMyDemandsRequest) (*ListMyDemandsReply, error)
	PreviewTripPrice(context.Context, *PreviewTripPriceRequest) (*PreviewTripPriceReply, error)
	PublishDemand(context.Context, *PublishDemandRequest) (*PublishDemandReply, error)
	PublishTrip(context.Context, *PublishTripRequest) (*PublishTripReply, error)
	SearchTrips(context.Context, *SearchTripsRequest) (*SearchTripsReply, error)
	SuggestLocations(context.Context, *SuggestLocationsRequest) (*SuggestLocationsReply, error)
	UpdateTripStatus(context.Context, *UpdateTripStatusRequest) (*UpdateTripStatusReply, error)
	ValidateLocation(context.Context, *ValidateLocationRequest) (*ValidateLocationReply, error)
}

func RegisterTripServiceHTTPServer(s *http.Server, srv TripServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/trips", _TripService_SearchTrips0_HTTP_Handler(srv))
	r.GET("/v1/trips/{id}", _TripService_GetTripDetail0_HTTP_Handler(srv))
	r.POST("/v1/driver/trips", _TripService_PublishTrip0_HTTP_Handler(srv))
	r.POST("/v1/driver/trips/locations/validate", _TripService_ValidateLocation0_HTTP_Handler(srv))
	r.POST("/v1/driver/trips/price-preview", _TripService_PreviewTripPrice0_HTTP_Handler(srv))
	r.POST("/v1/driver/trips/locations/suggest", _TripService_SuggestLocations0_HTTP_Handler(srv))
	r.GET("/v1/driver/trips", _TripService_ListDriverTrips0_HTTP_Handler(srv))
	r.PUT("/v1/driver/trips/{id}/status", _TripService_UpdateTripStatus0_HTTP_Handler(srv))
	r.GET("/v1/coupons", _TripService_ListCoupons0_HTTP_Handler(srv))
	r.POST("/v1/coupons/claim", _TripService_ClaimCoupon0_HTTP_Handler(srv))
	r.POST("/v1/trips/demands", _TripService_PublishDemand0_HTTP_Handler(srv))
	r.GET("/v1/trips/demands/mine", _TripService_ListMyDemands0_HTTP_Handler(srv))
	r.POST("/v1/trips/demands/{id}/cancel", _TripService_CancelDemand0_HTTP_Handler(srv))
	r.DELETE("/v1/driver/trips/{id}", _TripService_DeleteTrip0_HTTP_Handler(srv))
}

func _TripService_SearchTrips0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchTripsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceSearchTrips)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchTrips(ctx, req.(*SearchTripsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchTripsReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_GetTripDetail0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTripDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceGetTripDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTripDetail(ctx, req.(*GetTripDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTripDetailReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_PublishTrip0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishTripRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServicePublishTrip)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishTrip(ctx, req.(*PublishTripRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishTripReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_ValidateLocation0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidateLocationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceValidateLocation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ValidateLocation(ctx, req.(*ValidateLocationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidateLocationReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_PreviewTripPrice0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewTripPriceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServicePreviewTripPrice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewTripPrice(ctx, req.(*PreviewTripPriceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewTripPriceReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_SuggestLocations0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SuggestLocationsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceSuggestLocations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SuggestLocations(ctx, req.(*SuggestLocationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SuggestLocationsReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_ListDriverTrips0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDriverTripsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceListDriverTrips)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDriverTrips(ctx, req.(*ListDriverTripsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDriverTripsReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_UpdateTripStatus0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTripStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceUpdateTripStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTripStatus(ctx, req.(*UpdateTripStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTripStatusReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_ListCoupons0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCouponsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceListCoupons)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCoupons(ctx, req.(*ListCouponsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCouponsReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_ClaimCoupon0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimCouponRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceClaimCoupon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimCoupon(ctx, req.(*ClaimCouponRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClaimCouponReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_PublishDemand0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishDemandRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServicePublishDemand)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishDemand(ctx, req.(*PublishDemandRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishDemandReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_ListMyDemands0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMyDemandsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceListMyDemands)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyDemands(ctx, req.(*ListMyDemandsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMyDemandsReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_CancelDemand0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelDemandRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceCancelDemand)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelDemand(ctx, req.(*CancelDemandRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelDemandReply)
		return ctx.Result(200, reply)
	}
}

func _TripService_DeleteTrip0_HTTP_Handler(srv TripServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTripRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTripServiceDeleteTrip)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTrip(ctx, req.(*DeleteTripRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTripReply)
		return ctx.Result(200, reply)
	}
}

type TripServiceHTTPClient interface {
	CancelDemand(ctx context.Context, req *CancelDemandRequest, opts ...http.CallOption) (rsp *CancelDemandReply, err error)
	ClaimCoupon(ctx context.Context, req *ClaimCouponRequest, opts ...http.CallOption) (rsp *ClaimCouponReply, err error)
	DeleteTrip(ctx context.Context, req *DeleteTripRequest, opts ...http.CallOption) (rsp *DeleteTripReply, err error)
	GetTripDetail(ctx context.Context, req *GetTripDetailRequest, opts ...http.CallOption) (rsp *GetTripDetailReply, err error)
	ListCoupons(ctx context.Context, req *ListCouponsRequest, opts ...http.CallOption) (rsp *ListCouponsReply, err error)
	ListDriverTrips(ctx context.Context, req *ListDriverTripsRequest, opts ...http.CallOption) (rsp *ListDriverTripsReply, err error)
	ListMyDemands(ctx context.Context, req *ListMyDemandsRequest, opts ...http.CallOption) (rsp *ListMyDemandsReply, err error)
	PreviewTripPrice(ctx context.Context, req *PreviewTripPriceRequest, opts ...http.CallOption) (rsp *PreviewTripPriceReply, err error)
	PublishDemand(ctx context.Context, req *PublishDemandRequest, opts ...http.CallOption) (rsp *PublishDemandReply, err error)
	PublishTrip(ctx context.Context, req *PublishTripRequest, opts ...http.CallOption) (rsp *PublishTripReply, err error)
	SearchTrips(ctx context.Context, req *SearchTripsRequest, opts ...http.CallOption) (rsp *SearchTripsReply, err error)
	SuggestLocations(ctx context.Context, req *SuggestLocationsRequest, opts ...http.CallOption) (rsp *SuggestLocationsReply, err error)
	UpdateTripStatus(ctx context.Context, req *UpdateTripStatusRequest, opts ...http.CallOption) (rsp *UpdateTripStatusReply, err error)
	ValidateLocation(ctx context.Context, req *ValidateLocationRequest, opts ...http.CallOption) (rsp *ValidateLocationReply, err error)
}

type TripServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTripServiceHTTPClient(client *http.Client) TripServiceHTTPClient {
	return &TripServiceHTTPClientImpl{client}
}

func (c *TripServiceHTTPClientImpl) CancelDemand(ctx context.Context, in *CancelDemandRequest, opts ...http.CallOption) (*CancelDemandReply, error) {
	var out CancelDemandReply
	pattern := "/v1/trips/demands/{id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServiceCancelDemand))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...http.CallOption) (*ClaimCouponReply, error) {
	var out ClaimCouponReply
	pattern := "/v1/coupons/claim"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServiceClaimCoupon))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) DeleteTrip(ctx context.Context, in *DeleteTripRequest, opts ...http.CallOption) (*DeleteTripReply, error) {
	var out DeleteTripReply
	pattern := "/v1/driver/trips/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTripServiceDeleteTrip))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) GetTripDetail(ctx context.Context, in *GetTripDetailRequest, opts ...http.CallOption) (*GetTripDetailReply, error) {
	var out GetTripDetailReply
	pattern := "/v1/trips/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTripServiceGetTripDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...http.CallOption) (*ListCouponsReply, error) {
	var out ListCouponsReply
	pattern := "/v1/coupons"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTripServiceListCoupons))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) ListDriverTrips(ctx context.Context, in *ListDriverTripsRequest, opts ...http.CallOption) (*ListDriverTripsReply, error) {
	var out ListDriverTripsReply
	pattern := "/v1/driver/trips"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTripServiceListDriverTrips))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) ListMyDemands(ctx context.Context, in *ListMyDemandsRequest, opts ...http.CallOption) (*ListMyDemandsReply, error) {
	var out ListMyDemandsReply
	pattern := "/v1/trips/demands/mine"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTripServiceListMyDemands))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) PreviewTripPrice(ctx context.Context, in *PreviewTripPriceRequest, opts ...http.CallOption) (*PreviewTripPriceReply, error) {
	var out PreviewTripPriceReply
	pattern := "/v1/driver/trips/price-preview"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServicePreviewTripPrice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) PublishDemand(ctx context.Context, in *PublishDemandRequest, opts ...http.CallOption) (*PublishDemandReply, error) {
	var out PublishDemandReply
	pattern := "/v1/trips/demands"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServicePublishDemand))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) PublishTrip(ctx context.Context, in *PublishTripRequest, opts ...http.CallOption) (*PublishTripReply, error) {
	var out PublishTripReply
	pattern := "/v1/driver/trips"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServicePublishTrip))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) SearchTrips(ctx context.Context, in *SearchTripsRequest, opts ...http.CallOption) (*SearchTripsReply, error) {
	var out SearchTripsReply
	pattern := "/v1/trips"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTripServiceSearchTrips))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) SuggestLocations(ctx context.Context, in *SuggestLocationsRequest, opts ...http.CallOption) (*SuggestLocationsReply, error) {
	var out SuggestLocationsReply
	pattern := "/v1/driver/trips/locations/suggest"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServiceSuggestLocations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) UpdateTripStatus(ctx context.Context, in *UpdateTripStatusRequest, opts ...http.CallOption) (*UpdateTripStatusReply, error) {
	var out UpdateTripStatusReply
	pattern := "/v1/driver/trips/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServiceUpdateTripStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TripServiceHTTPClientImpl) ValidateLocation(ctx context.Context, in *ValidateLocationRequest, opts ...http.CallOption) (*ValidateLocationReply, error) {
	var out ValidateLocationReply
	pattern := "/v1/driver/trips/locations/validate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTripServiceValidateLocation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
