// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: driver/v1/driver.proto

package driverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverService_EnsureDriver_FullMethodName         = "/driver.v1.DriverService/EnsureDriver"
	DriverService_GetDriver_FullMethodName            = "/driver.v1.DriverService/GetDriver"
	DriverService_UpdateDriver_FullMethodName         = "/driver.v1.DriverService/UpdateDriver"
	DriverService_SubmitCertification_FullMethodName  = "/driver.v1.DriverService/SubmitCertification"
	DriverService_GetCertification_FullMethodName     = "/driver.v1.DriverService/GetCertification"
	DriverService_SaveVehicle_FullMethodName          = "/driver.v1.DriverService/SaveVehicle"
	DriverService_UpdateVehicle_FullMethodName        = "/driver.v1.DriverService/UpdateVehicle"
	DriverService_DeleteVehicle_FullMethodName        = "/driver.v1.DriverService/DeleteVehicle"
	DriverService_ListVehicles_FullMethodName         = "/driver.v1.DriverService/ListVehicles"
	DriverService_ListMessages_FullMethodName         = "/driver.v1.DriverService/ListMessages"
	DriverService_AckMessage_FullMethodName           = "/driver.v1.DriverService/AckMessage"
	DriverService_ReportDriverLocation_FullMethodName = "/driver.v1.DriverService/ReportDriverLocation"
	DriverService_ReplayDriverTrack_FullMethodName    = "/driver.v1.DriverService/ReplayDriverTrack"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	EnsureDriver(ctx context.Context, in *EnsureDriverRequest, opts ...grpc.CallOption) (*DriverProfileReply, error)
	GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*DriverProfileReply, error)
	UpdateDriver(ctx context.Context, in *UpdateDriverRequest, opts ...grpc.CallOption) (*DriverProfileReply, error)
	SubmitCertification(ctx context.Context, in *SubmitCertificationRequest, opts ...grpc.CallOption) (*CertificationReply, error)
	GetCertification(ctx context.Context, in *GetCertificationRequest, opts ...grpc.CallOption) (*CertificationReply, error)
	SaveVehicle(ctx context.Context, in *SaveVehicleRequest, opts ...grpc.CallOption) (*VehicleReply, error)
	UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*VehicleReply, error)
	DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*DeleteVehicleReply, error)
	ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (*ListVehiclesReply, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesReply, error)
	AckMessage(ctx context.Context, in *AckMessageRequest, opts ...grpc.CallOption) (*AckMessageReply, error)
	ReportDriverLocation(ctx context.Context, in *ReportDriverLocationRequest, opts ...grpc.CallOption) (*DriverLocationReply, error)
	ReplayDriverTrack(ctx context.Context, in *ReplayDriverTrackRequest, opts ...grpc.CallOption) (*ReplayDriverTrackReply, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) EnsureDriver(ctx context.Context, in *EnsureDriverRequest, opts ...grpc.CallOption) (*DriverProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverProfileReply)
	err := c.cc.Invoke(ctx, DriverService_EnsureDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetDriver(ctx context.Context, in *GetDriverRequest, opts ...grpc.CallOption) (*DriverProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverProfileReply)
	err := c.cc.Invoke(ctx, DriverService_GetDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateDriver(ctx context.Context, in *UpdateDriverRequest, opts ...grpc.CallOption) (*DriverProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverProfileReply)
	err := c.cc.Invoke(ctx, DriverService_UpdateDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) SubmitCertification(ctx context.Context, in *SubmitCertificationRequest, opts ...grpc.CallOption) (*CertificationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificationReply)
	err := c.cc.Invoke(ctx, DriverService_SubmitCertification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetCertification(ctx context.Context, in *GetCertificationRequest, opts ...grpc.CallOption) (*CertificationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificationReply)
	err := c.cc.Invoke(ctx, DriverService_GetCertification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) SaveVehicle(ctx context.Context, in *SaveVehicleRequest, opts ...grpc.CallOption) (*VehicleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VehicleReply)
	err := c.cc.Invoke(ctx, DriverService_SaveVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*VehicleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VehicleReply)
	err := c.cc.Invoke(ctx, DriverService_UpdateVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*DeleteVehicleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVehicleReply)
	err := c.cc.Invoke(ctx, DriverService_DeleteVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (*ListVehiclesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVehiclesReply)
	err := c.cc.Invoke(ctx, DriverService_ListVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesReply)
	err := c.cc.Invoke(ctx, DriverService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) AckMessage(ctx context.Context, in *AckMessageRequest, opts ...grpc.CallOption) (*AckMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckMessageReply)
	err := c.cc.Invoke(ctx, DriverService_AckMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ReportDriverLocation(ctx context.Context, in *ReportDriverLocationRequest, opts ...grpc.CallOption) (*DriverLocationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverLocationReply)
	err := c.cc.Invoke(ctx, DriverService_ReportDriverLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ReplayDriverTrack(ctx context.Context, in *ReplayDriverTrackRequest, opts ...grpc.CallOption) (*ReplayDriverTrackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayDriverTrackReply)
	err := c.cc.Invoke(ctx, DriverService_ReplayDriverTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	EnsureDriver(context.Context, *EnsureDriverRequest) (*DriverProfileReply, error)
	GetDriver(context.Context, *GetDriverRequest) (*DriverProfileReply, error)
	UpdateDriver(context.Context, *UpdateDriverRequest) (*DriverProfileReply, error)
	SubmitCertification(context.Context, *SubmitCertificationRequest) (*CertificationReply, error)
	GetCertification(context.Context, *GetCertificationRequest) (*CertificationReply, error)
	SaveVehicle(context.Context, *SaveVehicleRequest) (*VehicleReply, error)
	UpdateVehicle(context.Context, *UpdateVehicleRequest) (*VehicleReply, error)
	DeleteVehicle(context.Context, *DeleteVehicleRequest) (*DeleteVehicleReply, error)
	ListVehicles(context.Context, *ListVehiclesRequest) (*ListVehiclesReply, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesReply, error)
	AckMessage(context.Context, *AckMessageRequest) (*AckMessageReply, error)
	ReportDriverLocation(context.Context, *ReportDriverLocationRequest) (*DriverLocationReply, error)
	ReplayDriverTrack(context.Context, *ReplayDriverTrackRequest) (*ReplayDriverTrackReply, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) EnsureDriver(context.Context, *EnsureDriverRequest) (*DriverProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureDriver not implemented")
}
func (UnimplementedDriverServiceServer) GetDriver(context.Context, *GetDriverRequest) (*DriverProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriver not implemented")
}
func (UnimplementedDriverServiceServer) UpdateDriver(context.Context, *UpdateDriverRequest) (*DriverProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDriver not implemented")
}
func (UnimplementedDriverServiceServer) SubmitCertification(context.Context, *SubmitCertificationRequest) (*CertificationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCertification not implemented")
}
func (UnimplementedDriverServiceServer) GetCertification(context.Context, *GetCertificationRequest) (*CertificationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertification not implemented")
}
func (UnimplementedDriverServiceServer) SaveVehicle(context.Context, *SaveVehicleRequest) (*VehicleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveVehicle not implemented")
}
func (UnimplementedDriverServiceServer) UpdateVehicle(context.Context, *UpdateVehicleRequest) (*VehicleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVehicle not implemented")
}
func (UnimplementedDriverServiceServer) DeleteVehicle(context.Context, *DeleteVehicleRequest) (*DeleteVehicleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVehicle not implemented")
}
func (UnimplementedDriverServiceServer) ListVehicles(context.Context, *ListVehiclesRequest) (*ListVehiclesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVehicles not implemented")
}
func (UnimplementedDriverServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedDriverServiceServer) AckMessage(context.Context, *AckMessageRequest) (*AckMessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AckMessage not implemented")
}
func (UnimplementedDriverServiceServer) ReportDriverLocation(context.Context, *ReportDriverLocationRequest) (*DriverLocationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDriverLocation not implemented")
}
func (UnimplementedDriverServiceServer) ReplayDriverTrack(context.Context, *ReplayDriverTrackRequest) (*ReplayDriverTrackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayDriverTrack not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_EnsureDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).EnsureDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_EnsureDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).EnsureDriver(ctx, req.(*EnsureDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetDriver(ctx, req.(*GetDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateDriver(ctx, req.(*UpdateDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_SubmitCertification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCertificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).SubmitCertification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_SubmitCertification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).SubmitCertification(ctx, req.(*SubmitCertificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetCertification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetCertification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetCertification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetCertification(ctx, req.(*GetCertificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_SaveVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).SaveVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_SaveVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).SaveVehicle(ctx, req.(*SaveVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateVehicle(ctx, req.(*UpdateVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_DeleteVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).DeleteVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_DeleteVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).DeleteVehicle(ctx, req.(*DeleteVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ListVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ListVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ListVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ListVehicles(ctx, req.(*ListVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_AckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).AckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_AckMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).AckMessage(ctx, req.(*AckMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ReportDriverLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDriverLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ReportDriverLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ReportDriverLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ReportDriverLocation(ctx, req.(*ReportDriverLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ReplayDriverTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayDriverTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ReplayDriverTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ReplayDriverTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ReplayDriverTrack(ctx, req.(*ReplayDriverTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.v1.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureDriver",
			Handler:    _DriverService_EnsureDriver_Handler,
		},
		{
			MethodName: "GetDriver",
			Handler:    _DriverService_GetDriver_Handler,
		},
		{
			MethodName: "UpdateDriver",
			Handler:    _DriverService_UpdateDriver_Handler,
		},
		{
			MethodName: "SubmitCertification",
			Handler:    _DriverService_SubmitCertification_Handler,
		},
		{
			MethodName: "GetCertification",
			Handler:    _DriverService_GetCertification_Handler,
		},
		{
			MethodName: "SaveVehicle",
			Handler:    _DriverService_SaveVehicle_Handler,
		},
		{
			MethodName: "UpdateVehicle",
			Handler:    _DriverService_UpdateVehicle_Handler,
		},
		{
			MethodName: "DeleteVehicle",
			Handler:    _DriverService_DeleteVehicle_Handler,
		},
		{
			MethodName: "ListVehicles",
			Handler:    _DriverService_ListVehicles_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _DriverService_ListMessages_Handler,
		},
		{
			MethodName: "AckMessage",
			Handler:    _DriverService_AckMessage_Handler,
		},
		{
			MethodName: "ReportDriverLocation",
			Handler:    _DriverService_ReportDriverLocation_Handler,
		},
		{
			MethodName: "ReplayDriverTrack",
			Handler:    _DriverService_ReplayDriverTrack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver/v1/driver.proto",
}
