// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: driver/v1/driver.proto

package driverv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDriverRequest) Reset() {
	*x = EnsureDriverRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDriverRequest) ProtoMessage() {}

func (x *EnsureDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDriverRequest.ProtoReflect.Descriptor instead.
func (*EnsureDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureDriverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnsureDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverRequest) Reset() {
	*x = GetDriverRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRequest) ProtoMessage() {}

func (x *GetDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRequest.ProtoReflect.Descriptor instead.
func (*GetDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ServiceStatus int32                  `protobuf:"varint,5,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverRequest) Reset() {
	*x = UpdateDriverRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverRequest) ProtoMessage() {}

func (x *UpdateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDriverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateDriverRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateDriverRequest) GetServiceStatus() int32 {
	if x != nil {
		return x.ServiceStatus
	}
	return 0
}

type SubmitCertificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RealName         string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCardNo         string                 `protobuf:"bytes,3,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	LicenseNo        string                 `protobuf:"bytes,4,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	LicenseType      string                 `protobuf:"bytes,5,opt,name=license_type,json=licenseType,proto3" json:"license_type,omitempty"`
	City             string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	VehicleLicenseNo string                 `protobuf:"bytes,7,opt,name=vehicle_license_no,json=vehicleLicenseNo,proto3" json:"vehicle_license_no,omitempty"`
	VehiclePhotoUrl  string                 `protobuf:"bytes,8,opt,name=vehicle_photo_url,json=vehiclePhotoUrl,proto3" json:"vehicle_photo_url,omitempty"`
	FacePhotoUrl     string                 `protobuf:"bytes,9,opt,name=face_photo_url,json=facePhotoUrl,proto3" json:"face_photo_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitCertificationRequest) Reset() {
	*x = SubmitCertificationRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCertificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCertificationRequest) ProtoMessage() {}

func (x *SubmitCertificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCertificationRequest.ProtoReflect.Descriptor instead.
func (*SubmitCertificationRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitCertificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitCertificationRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *SubmitCertificationRequest) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

func (x *SubmitCertificationRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *SubmitCertificationRequest) GetLicenseType() string {
	if x != nil {
		return x.LicenseType
	}
	return ""
}

func (x *SubmitCertificationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SubmitCertificationRequest) GetVehicleLicenseNo() string {
	if x != nil {
		return x.VehicleLicenseNo
	}
	return ""
}

func (x *SubmitCertificationRequest) GetVehiclePhotoUrl() string {
	if x != nil {
		return x.VehiclePhotoUrl
	}
	return ""
}

func (x *SubmitCertificationRequest) GetFacePhotoUrl() string {
	if x != nil {
		return x.FacePhotoUrl
	}
	return ""
}

type GetCertificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificationRequest) Reset() {
	*x = GetCertificationRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificationRequest) ProtoMessage() {}

func (x *GetCertificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificationRequest.ProtoReflect.Descriptor instead.
func (*GetCertificationRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{4}
}

func (x *GetCertificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SaveVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlateNo       string                 `protobuf:"bytes,2,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	VehicleType   string                 `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Seats         int32                  `protobuf:"varint,7,opt,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveVehicleRequest) Reset() {
	*x = SaveVehicleRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVehicleRequest) ProtoMessage() {}

func (x *SaveVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVehicleRequest.ProtoReflect.Descriptor instead.
func (*SaveVehicleRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{5}
}

func (x *SaveVehicleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveVehicleRequest) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *SaveVehicleRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *SaveVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SaveVehicleRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *SaveVehicleRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *SaveVehicleRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

type UpdateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	PlateNo       string                 `protobuf:"bytes,3,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	VehicleType   string                 `protobuf:"bytes,7,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Seats         int32                  `protobuf:"varint,8,opt,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVehicleRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UpdateVehicleRequest) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *UpdateVehicleRequest) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *UpdateVehicleRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateVehicleRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *UpdateVehicleRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVehicleRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DeleteVehicleRequest) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{8}
}

func (x *ListVehiclesRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{9}
}

func (x *ListMessagesRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type AckMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageRequest) Reset() {
	*x = AckMessageRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageRequest) ProtoMessage() {}

func (x *AckMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageRequest.ProtoReflect.Descriptor instead.
func (*AckMessageRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{10}
}

func (x *AckMessageRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *AckMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ReportDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	ReportedAt    string                 `protobuf:"bytes,7,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDriverLocationRequest) Reset() {
	*x = ReportDriverLocationRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDriverLocationRequest) ProtoMessage() {}

func (x *ReportDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*ReportDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{11}
}

func (x *ReportDriverLocationRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ReportDriverLocationRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReportDriverLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ReportDriverLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ReportDriverLocationRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *ReportDriverLocationRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *ReportDriverLocationRequest) GetReportedAt() string {
	if x != nil {
		return x.ReportedAt
	}
	return ""
}

type ReplayDriverTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDriverTrackRequest) Reset() {
	*x = ReplayDriverTrackRequest{}
	mi := &file_driver_v1_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDriverTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDriverTrackRequest) ProtoMessage() {}

func (x *ReplayDriverTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDriverTrackRequest.ProtoReflect.Descriptor instead.
func (*ReplayDriverTrackRequest) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{12}
}

func (x *ReplayDriverTrackRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ReplayDriverTrackRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReplayDriverTrackRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReplayDriverTrackRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DriverProfile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone               string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl           string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ServiceStatus       int32                  `protobuf:"varint,5,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	CertificationStatus int32                  `protobuf:"varint,6,opt,name=certification_status,json=certificationStatus,proto3" json:"certification_status,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DriverProfile) Reset() {
	*x = DriverProfile{}
	mi := &file_driver_v1_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfile) ProtoMessage() {}

func (x *DriverProfile) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfile.ProtoReflect.Descriptor instead.
func (*DriverProfile) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{13}
}

func (x *DriverProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *DriverProfile) GetServiceStatus() int32 {
	if x != nil {
		return x.ServiceStatus
	}
	return 0
}

func (x *DriverProfile) GetCertificationStatus() int32 {
	if x != nil {
		return x.CertificationStatus
	}
	return 0
}

func (x *DriverProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DriverProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DriverCertification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId         int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RealName         string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCardNo         string                 `protobuf:"bytes,4,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	LicenseNo        string                 `protobuf:"bytes,5,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	LicenseType      string                 `protobuf:"bytes,6,opt,name=license_type,json=licenseType,proto3" json:"license_type,omitempty"`
	City             string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	VehicleLicenseNo string                 `protobuf:"bytes,8,opt,name=vehicle_license_no,json=vehicleLicenseNo,proto3" json:"vehicle_license_no,omitempty"`
	VehiclePhotoUrl  string                 `protobuf:"bytes,9,opt,name=vehicle_photo_url,json=vehiclePhotoUrl,proto3" json:"vehicle_photo_url,omitempty"`
	FacePhotoUrl     string                 `protobuf:"bytes,10,opt,name=face_photo_url,json=facePhotoUrl,proto3" json:"face_photo_url,omitempty"`
	Status           int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	RejectReason     string                 `protobuf:"bytes,12,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DriverCertification) Reset() {
	*x = DriverCertification{}
	mi := &file_driver_v1_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCertification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCertification) ProtoMessage() {}

func (x *DriverCertification) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCertification.ProtoReflect.Descriptor instead.
func (*DriverCertification) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{14}
}

func (x *DriverCertification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverCertification) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverCertification) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *DriverCertification) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

func (x *DriverCertification) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *DriverCertification) GetLicenseType() string {
	if x != nil {
		return x.LicenseType
	}
	return ""
}

func (x *DriverCertification) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DriverCertification) GetVehicleLicenseNo() string {
	if x != nil {
		return x.VehicleLicenseNo
	}
	return ""
}

func (x *DriverCertification) GetVehiclePhotoUrl() string {
	if x != nil {
		return x.VehiclePhotoUrl
	}
	return ""
}

func (x *DriverCertification) GetFacePhotoUrl() string {
	if x != nil {
		return x.FacePhotoUrl
	}
	return ""
}

func (x *DriverCertification) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DriverCertification) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *DriverCertification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DriverCertification) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DriverVehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId      int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PlateNo       string                 `protobuf:"bytes,3,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	VehicleType   string                 `protobuf:"bytes,7,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Seats         int32                  `protobuf:"varint,8,opt,name=seats,proto3" json:"seats,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AuditId       int64                  `protobuf:"varint,12,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	ReviewStatus  int32                  `protobuf:"varint,13,opt,name=review_status,json=reviewStatus,proto3" json:"review_status,omitempty"`
	RejectReason  string                 `protobuf:"bytes,14,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	Source        string                 `protobuf:"bytes,15,opt,name=source,proto3" json:"source,omitempty"`
	CanEdit       bool                   `protobuf:"varint,16,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	CanDelete     bool                   `protobuf:"varint,17,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverVehicle) Reset() {
	*x = DriverVehicle{}
	mi := &file_driver_v1_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverVehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverVehicle) ProtoMessage() {}

func (x *DriverVehicle) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverVehicle.ProtoReflect.Descriptor instead.
func (*DriverVehicle) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{15}
}

func (x *DriverVehicle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverVehicle) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverVehicle) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *DriverVehicle) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DriverVehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DriverVehicle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *DriverVehicle) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *DriverVehicle) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *DriverVehicle) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DriverVehicle) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DriverVehicle) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DriverVehicle) GetAuditId() int64 {
	if x != nil {
		return x.AuditId
	}
	return 0
}

func (x *DriverVehicle) GetReviewStatus() int32 {
	if x != nil {
		return x.ReviewStatus
	}
	return 0
}

func (x *DriverVehicle) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *DriverVehicle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DriverVehicle) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *DriverVehicle) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

type DriverMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Delivered     bool                   `protobuf:"varint,5,opt,name=delivered,proto3" json:"delivered,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverMessage) Reset() {
	*x = DriverMessage{}
	mi := &file_driver_v1_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverMessage) ProtoMessage() {}

func (x *DriverMessage) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverMessage.ProtoReflect.Descriptor instead.
func (*DriverMessage) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{16}
}

func (x *DriverMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DriverMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DriverMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *DriverMessage) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *DriverMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DriverLocationPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId      int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,7,opt,name=heading,proto3" json:"heading,omitempty"`
	ReportedAt    string                 `protobuf:"bytes,8,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocationPoint) Reset() {
	*x = DriverLocationPoint{}
	mi := &file_driver_v1_driver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocationPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocationPoint) ProtoMessage() {}

func (x *DriverLocationPoint) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocationPoint.ProtoReflect.Descriptor instead.
func (*DriverLocationPoint) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{17}
}

func (x *DriverLocationPoint) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverLocationPoint) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverLocationPoint) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DriverLocationPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DriverLocationPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DriverLocationPoint) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *DriverLocationPoint) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *DriverLocationPoint) GetReportedAt() string {
	if x != nil {
		return x.ReportedAt
	}
	return ""
}

func (x *DriverLocationPoint) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DriverProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        *DriverProfile         `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverProfileReply) Reset() {
	*x = DriverProfileReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfileReply) ProtoMessage() {}

func (x *DriverProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfileReply.ProtoReflect.Descriptor instead.
func (*DriverProfileReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{18}
}

func (x *DriverProfileReply) GetDriver() *DriverProfile {
	if x != nil {
		return x.Driver
	}
	return nil
}

type CertificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certification *DriverCertification   `protobuf:"bytes,1,opt,name=certification,proto3" json:"certification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificationReply) Reset() {
	*x = CertificationReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificationReply) ProtoMessage() {}

func (x *CertificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificationReply.ProtoReflect.Descriptor instead.
func (*CertificationReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{19}
}

func (x *CertificationReply) GetCertification() *DriverCertification {
	if x != nil {
		return x.Certification
	}
	return nil
}

type VehicleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *DriverVehicle         `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleReply) Reset() {
	*x = VehicleReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleReply) ProtoMessage() {}

func (x *VehicleReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleReply.ProtoReflect.Descriptor instead.
func (*VehicleReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{20}
}

func (x *VehicleReply) GetVehicle() *DriverVehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type DeleteVehicleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleReply) Reset() {
	*x = DeleteVehicleReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleReply) ProtoMessage() {}

func (x *DeleteVehicleReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleReply.ProtoReflect.Descriptor instead.
func (*DeleteVehicleReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteVehicleReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListVehiclesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DriverVehicle       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesReply) Reset() {
	*x = ListVehiclesReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesReply) ProtoMessage() {}

func (x *ListVehiclesReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesReply.ProtoReflect.Descriptor instead.
func (*ListVehiclesReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{22}
}

func (x *ListVehiclesReply) GetItems() []*DriverVehicle {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListMessagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DriverMessage       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesReply) Reset() {
	*x = ListMessagesReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesReply) ProtoMessage() {}

func (x *ListMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesReply.ProtoReflect.Descriptor instead.
func (*ListMessagesReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{23}
}

func (x *ListMessagesReply) GetItems() []*DriverMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type AckMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageReply) Reset() {
	*x = AckMessageReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageReply) ProtoMessage() {}

func (x *AckMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageReply.ProtoReflect.Descriptor instead.
func (*AckMessageReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{24}
}

func (x *AckMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DriverLocationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *DriverLocationPoint   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocationReply) Reset() {
	*x = DriverLocationReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocationReply) ProtoMessage() {}

func (x *DriverLocationReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocationReply.ProtoReflect.Descriptor instead.
func (*DriverLocationReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{25}
}

func (x *DriverLocationReply) GetLocation() *DriverLocationPoint {
	if x != nil {
		return x.Location
	}
	return nil
}

type ReplayDriverTrackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*DriverLocationPoint `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDriverTrackReply) Reset() {
	*x = ReplayDriverTrackReply{}
	mi := &file_driver_v1_driver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDriverTrackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDriverTrackReply) ProtoMessage() {}

func (x *ReplayDriverTrackReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_v1_driver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDriverTrackReply.ProtoReflect.Descriptor instead.
func (*ReplayDriverTrackReply) Descriptor() ([]byte, []int) {
	return file_driver_v1_driver_proto_rawDescGZIP(), []int{26}
}

func (x *ReplayDriverTrackReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReplayDriverTrackReply) GetItems() []*DriverLocationPoint {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_driver_v1_driver_proto protoreflect.FileDescriptor

const file_driver_v1_driver_proto_rawDesc = "" +
	"\n" +
	"\x16driver/v1/driver.proto\x12\tdriver.v1\x1a\x1cgoogle/api/annotations.proto\";\n" +
	"\x13EnsureDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"\"\n" +
	"\x10GetDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x95\x01\n" +
	"\x13UpdateDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12%\n" +
	"\x0eservice_status\x18\x05 \x01(\x05R\rserviceStatus\"\xbd\x02\n" +
	"\x1aSubmitCertificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x1c\n" +
	"\n" +
	"id_card_no\x18\x03 \x01(\tR\bidCardNo\x12\x1d\n" +
	"\n" +
	"license_no\x18\x04 \x01(\tR\tlicenseNo\x12!\n" +
	"\flicense_type\x18\x05 \x01(\tR\vlicenseType\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12,\n" +
	"\x12vehicle_license_no\x18\a \x01(\tR\x10vehicleLicenseNo\x12*\n" +
	"\x11vehicle_photo_url\x18\b \x01(\tR\x0fvehiclePhotoUrl\x12$\n" +
	"\x0eface_photo_url\x18\t \x01(\tR\ffacePhotoUrl\")\n" +
	"\x17GetCertificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xba\x01\n" +
	"\x12SaveVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bplate_no\x18\x02 \x01(\tR\aplateNo\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12!\n" +
	"\fvehicle_type\x18\x06 \x01(\tR\vvehicleType\x12\x14\n" +
	"\x05seats\x18\a \x01(\x05R\x05seats\"\xe8\x01\n" +
	"\x14UpdateVehicleRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\x12\x19\n" +
	"\bplate_no\x18\x03 \x01(\tR\aplateNo\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12!\n" +
	"\fvehicle_type\x18\a \x01(\tR\vvehicleType\x12\x14\n" +
	"\x05seats\x18\b \x01(\x05R\x05seats\"R\n" +
	"\x14DeleteVehicleRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\"%\n" +
	"\x13ListVehiclesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x13ListMessagesRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\"O\n" +
	"\x11AckMessageRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\"\xe0\x01\n" +
	"\x1bReportDriverLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12\x1f\n" +
	"\vreported_at\x18\a \x01(\tR\n" +
	"reportedAt\"\x83\x01\n" +
	"\x18ReplayDriverTrackRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x80\x02\n" +
	"\rDriverProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12%\n" +
	"\x0eservice_status\x18\x05 \x01(\x05R\rserviceStatus\x121\n" +
	"\x14certification_status\x18\x06 \x01(\x05R\x13certificationStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xce\x03\n" +
	"\x13DriverCertification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1c\n" +
	"\n" +
	"id_card_no\x18\x04 \x01(\tR\bidCardNo\x12\x1d\n" +
	"\n" +
	"license_no\x18\x05 \x01(\tR\tlicenseNo\x12!\n" +
	"\flicense_type\x18\x06 \x01(\tR\vlicenseType\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12,\n" +
	"\x12vehicle_license_no\x18\b \x01(\tR\x10vehicleLicenseNo\x12*\n" +
	"\x11vehicle_photo_url\x18\t \x01(\tR\x0fvehiclePhotoUrl\x12$\n" +
	"\x0eface_photo_url\x18\n" +
	" \x01(\tR\ffacePhotoUrl\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12#\n" +
	"\rreject_reason\x18\f \x01(\tR\frejectReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xdf\x03\n" +
	"\rDriverVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12\x19\n" +
	"\bplate_no\x18\x03 \x01(\tR\aplateNo\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12!\n" +
	"\fvehicle_type\x18\a \x01(\tR\vvehicleType\x12\x14\n" +
	"\x05seats\x18\b \x01(\x05R\x05seats\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x19\n" +
	"\baudit_id\x18\f \x01(\x03R\aauditId\x12#\n" +
	"\rreview_status\x18\r \x01(\x05R\freviewStatus\x12#\n" +
	"\rreject_reason\x18\x0e \x01(\tR\frejectReason\x12\x16\n" +
	"\x06source\x18\x0f \x01(\tR\x06source\x12\x19\n" +
	"\bcan_edit\x18\x10 \x01(\bR\acanEdit\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x11 \x01(\bR\tcanDelete\"\xa2\x01\n" +
	"\rDriverMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x1c\n" +
	"\tdelivered\x18\x05 \x01(\bR\tdelivered\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x87\x02\n" +
	"\x13DriverLocationPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\a \x01(\x01R\aheading\x12\x1f\n" +
	"\vreported_at\x18\b \x01(\tR\n" +
	"reportedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"F\n" +
	"\x12DriverProfileReply\x120\n" +
	"\x06driver\x18\x01 \x01(\v2\x18.driver.v1.DriverProfileR\x06driver\"Z\n" +
	"\x12CertificationReply\x12D\n" +
	"\rcertification\x18\x01 \x01(\v2\x1e.driver.v1.DriverCertificationR\rcertification\"B\n" +
	"\fVehicleReply\x122\n" +
	"\avehicle\x18\x01 \x01(\v2\x18.driver.v1.DriverVehicleR\avehicle\".\n" +
	"\x12DeleteVehicleReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x11ListVehiclesReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.driver.v1.DriverVehicleR\x05items\"C\n" +
	"\x11ListMessagesReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.driver.v1.DriverMessageR\x05items\"+\n" +
	"\x0fAckMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x13DriverLocationReply\x12:\n" +
	"\blocation\x18\x01 \x01(\v2\x1e.driver.v1.DriverLocationPointR\blocation\"d\n" +
	"\x16ReplayDriverTrackReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x124\n" +
	"\x05items\x18\x02 \x03(\v2\x1e.driver.v1.DriverLocationPointR\x05items2\xe1\f\n" +
	"\rDriverService\x12l\n" +
	"\fEnsureDriver\x12\x1e.driver.v1.EnsureDriverRequest\x1a\x1d.driver.v1.DriverProfileReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/drivers/ensure\x12a\n" +
	"\tGetDriver\x12\x1b.driver.v1.GetDriverRequest\x1a\x1d.driver.v1.DriverProfileReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/drivers/{id}\x12j\n" +
	"\fUpdateDriver\x12\x1e.driver.v1.UpdateDriverRequest\x1a\x1d.driver.v1.DriverProfileReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/drivers/{id}\x12\x86\x01\n" +
	"\x13SubmitCertification\x12%.driver.v1.SubmitCertificationRequest\x1a\x1d.driver.v1.CertificationReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/drivers/{id}/certification\x12}\n" +
	"\x10GetCertification\x12\".driver.v1.GetCertificationRequest\x1a\x1d.driver.v1.CertificationReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/drivers/{id}/certification\x12k\n" +
	"\vSaveVehicle\x12\x1d.driver.v1.SaveVehicleRequest\x1a\x17.driver.v1.VehicleReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/drivers/{id}/vehicles\x12\x83\x01\n" +
	"\rUpdateVehicle\x12\x1f.driver.v1.UpdateVehicleRequest\x1a\x17.driver.v1.VehicleReply\"8\x82\xd3\xe4\x93\x022:\x01*\x1a-/v1/drivers/{driver_id}/vehicles/{vehicle_id}\x12\x86\x01\n" +
	"\rDeleteVehicle\x12\x1f.driver.v1.DeleteVehicleRequest\x1a\x1d.driver.v1.DeleteVehicleReply\"5\x82\xd3\xe4\x93\x02/*-/v1/drivers/{driver_id}/vehicles/{vehicle_id}\x12o\n" +
	"\fListVehicles\x12\x1e.driver.v1.ListVehiclesRequest\x1a\x1c.driver.v1.ListVehiclesReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/drivers/{id}/vehicles\x12v\n" +
	"\fListMessages\x12\x1e.driver.v1.ListMessagesRequest\x1a\x1c.driver.v1.ListMessagesReply\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/drivers/{driver_id}/messages\x12\x84\x01\n" +
	"\n" +
	"AckMessage\x12\x1c.driver.v1.AckMessageRequest\x1a\x1a.driver.v1.AckMessageReply\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v1/drivers/{driver_id}/messages/{message_id}/ack\x12\x92\x01\n" +
	"\x14ReportDriverLocation\x12&.driver.v1.ReportDriverLocationRequest\x1a\x1e.driver.v1.DriverLocationReply\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/drivers/{driver_id}/location/report\x12\x89\x01\n" +
	"\x11ReplayDriverTrack\x12#.driver.v1.ReplayDriverTrackRequest\x1a!.driver.v1.ReplayDriverTrackReply\",\x82\xd3\xe4\x93\x02&\x12$/v1/drivers/{driver_id}/track/replayB=Z;ride-hailing/services/driver-service/api/driver/v1;driverv1b\x06proto3"

var (
	file_driver_v1_driver_proto_rawDescOnce sync.Once
	file_driver_v1_driver_proto_rawDescData []byte
)

func file_driver_v1_driver_proto_rawDescGZIP() []byte {
	file_driver_v1_driver_proto_rawDescOnce.Do(func() {
		file_driver_v1_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_v1_driver_proto_rawDesc), len(file_driver_v1_driver_proto_rawDesc)))
	})
	return file_driver_v1_driver_proto_rawDescData
}

var file_driver_v1_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_driver_v1_driver_proto_goTypes = []any{
	(*EnsureDriverRequest)(nil),         // 0: driver.v1.EnsureDriverRequest
	(*GetDriverRequest)(nil),            // 1: driver.v1.GetDriverRequest
	(*UpdateDriverRequest)(nil),         // 2: driver.v1.UpdateDriverRequest
	(*SubmitCertificationRequest)(nil),  // 3: driver.v1.SubmitCertificationRequest
	(*GetCertificationRequest)(nil),     // 4: driver.v1.GetCertificationRequest
	(*SaveVehicleRequest)(nil),          // 5: driver.v1.SaveVehicleRequest
	(*UpdateVehicleRequest)(nil),        // 6: driver.v1.UpdateVehicleRequest
	(*DeleteVehicleRequest)(nil),        // 7: driver.v1.DeleteVehicleRequest
	(*ListVehiclesRequest)(nil),         // 8: driver.v1.ListVehiclesRequest
	(*ListMessagesRequest)(nil),         // 9: driver.v1.ListMessagesRequest
	(*AckMessageRequest)(nil),           // 10: driver.v1.AckMessageRequest
	(*ReportDriverLocationRequest)(nil), // 11: driver.v1.ReportDriverLocationRequest
	(*ReplayDriverTrackRequest)(nil),    // 12: driver.v1.ReplayDriverTrackRequest
	(*DriverProfile)(nil),               // 13: driver.v1.DriverProfile
	(*DriverCertification)(nil),         // 14: driver.v1.DriverCertification
	(*DriverVehicle)(nil),               // 15: driver.v1.DriverVehicle
	(*DriverMessage)(nil),               // 16: driver.v1.DriverMessage
	(*DriverLocationPoint)(nil),         // 17: driver.v1.DriverLocationPoint
	(*DriverProfileReply)(nil),          // 18: driver.v1.DriverProfileReply
	(*CertificationReply)(nil),          // 19: driver.v1.CertificationReply
	(*VehicleReply)(nil),                // 20: driver.v1.VehicleReply
	(*DeleteVehicleReply)(nil),          // 21: driver.v1.DeleteVehicleReply
	(*ListVehiclesReply)(nil),           // 22: driver.v1.ListVehiclesReply
	(*ListMessagesReply)(nil),           // 23: driver.v1.ListMessagesReply
	(*AckMessageReply)(nil),             // 24: driver.v1.AckMessageReply
	(*DriverLocationReply)(nil),         // 25: driver.v1.DriverLocationReply
	(*ReplayDriverTrackReply)(nil),      // 26: driver.v1.ReplayDriverTrackReply
}
var file_driver_v1_driver_proto_depIdxs = []int32{
	13, // 0: driver.v1.DriverProfileReply.driver:type_name -> driver.v1.DriverProfile
	14, // 1: driver.v1.CertificationReply.certification:type_name -> driver.v1.DriverCertification
	15, // 2: driver.v1.VehicleReply.vehicle:type_name -> driver.v1.DriverVehicle
	15, // 3: driver.v1.ListVehiclesReply.items:type_name -> driver.v1.DriverVehicle
	16, // 4: driver.v1.ListMessagesReply.items:type_name -> driver.v1.DriverMessage
	17, // 5: driver.v1.DriverLocationReply.location:type_name -> driver.v1.DriverLocationPoint
	17, // 6: driver.v1.ReplayDriverTrackReply.items:type_name -> driver.v1.DriverLocationPoint
	0,  // 7: driver.v1.DriverService.EnsureDriver:input_type -> driver.v1.EnsureDriverRequest
	1,  // 8: driver.v1.DriverService.GetDriver:input_type -> driver.v1.GetDriverRequest
	2,  // 9: driver.v1.DriverService.UpdateDriver:input_type -> driver.v1.UpdateDriverRequest
	3,  // 10: driver.v1.DriverService.SubmitCertification:input_type -> driver.v1.SubmitCertificationRequest
	4,  // 11: driver.v1.DriverService.GetCertification:input_type -> driver.v1.GetCertificationRequest
	5,  // 12: driver.v1.DriverService.SaveVehicle:input_type -> driver.v1.SaveVehicleRequest
	6,  // 13: driver.v1.DriverService.UpdateVehicle:input_type -> driver.v1.UpdateVehicleRequest
	7,  // 14: driver.v1.DriverService.DeleteVehicle:input_type -> driver.v1.DeleteVehicleRequest
	8,  // 15: driver.v1.DriverService.ListVehicles:input_type -> driver.v1.ListVehiclesRequest
	9,  // 16: driver.v1.DriverService.ListMessages:input_type -> driver.v1.ListMessagesRequest
	10, // 17: driver.v1.DriverService.AckMessage:input_type -> driver.v1.AckMessageRequest
	11, // 18: driver.v1.DriverService.ReportDriverLocation:input_type -> driver.v1.ReportDriverLocationRequest
	12, // 19: driver.v1.DriverService.ReplayDriverTrack:input_type -> driver.v1.ReplayDriverTrackRequest
	18, // 20: driver.v1.DriverService.EnsureDriver:output_type -> driver.v1.DriverProfileReply
	18, // 21: driver.v1.DriverService.GetDriver:output_type -> driver.v1.DriverProfileReply
	18, // 22: driver.v1.DriverService.UpdateDriver:output_type -> driver.v1.DriverProfileReply
	19, // 23: driver.v1.DriverService.SubmitCertification:output_type -> driver.v1.CertificationReply
	19, // 24: driver.v1.DriverService.GetCertification:output_type -> driver.v1.CertificationReply
	20, // 25: driver.v1.DriverService.SaveVehicle:output_type -> driver.v1.VehicleReply
	20, // 26: driver.v1.DriverService.UpdateVehicle:output_type -> driver.v1.VehicleReply
	21, // 27: driver.v1.DriverService.DeleteVehicle:output_type -> driver.v1.DeleteVehicleReply
	22, // 28: driver.v1.DriverService.ListVehicles:output_type -> driver.v1.ListVehiclesReply
	23, // 29: driver.v1.DriverService.ListMessages:output_type -> driver.v1.ListMessagesReply
	24, // 30: driver.v1.DriverService.AckMessage:output_type -> driver.v1.AckMessageReply
	25, // 31: driver.v1.DriverService.ReportDriverLocation:output_type -> driver.v1.DriverLocationReply
	26, // 32: driver.v1.DriverService.ReplayDriverTrack:output_type -> driver.v1.ReplayDriverTrackReply
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_driver_v1_driver_proto_init() }
func file_driver_v1_driver_proto_init() {
	if File_driver_v1_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_v1_driver_proto_rawDesc), len(file_driver_v1_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_v1_driver_proto_goTypes,
		DependencyIndexes: file_driver_v1_driver_proto_depIdxs,
		MessageInfos:      file_driver_v1_driver_proto_msgTypes,
	}.Build()
	File_driver_v1_driver_proto = out.File
	file_driver_v1_driver_proto_goTypes = nil
	file_driver_v1_driver_proto_depIdxs = nil
}
