// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: driver/v1/driver.proto

package driverv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDriverServiceAckMessage = "/driver.v1.DriverService/AckMessage"
const OperationDriverServiceDeleteVehicle = "/driver.v1.DriverService/DeleteVehicle"
const OperationDriverServiceEnsureDriver = "/driver.v1.DriverService/EnsureDriver"
const OperationDriverServiceGetCertification = "/driver.v1.DriverService/GetCertification"
const OperationDriverServiceGetDriver = "/driver.v1.DriverService/GetDriver"
const OperationDriverServiceListMessages = "/driver.v1.DriverService/ListMessages"
const OperationDriverServiceListVehicles = "/driver.v1.DriverService/ListVehicles"
const OperationDriverServiceReplayDriverTrack = "/driver.v1.DriverService/ReplayDriverTrack"
const OperationDriverServiceReportDriverLocation = "/driver.v1.DriverService/ReportDriverLocation"
const OperationDriverServiceSaveVehicle = "/driver.v1.DriverService/SaveVehicle"
const OperationDriverServiceSubmitCertification = "/driver.v1.DriverService/SubmitCertification"
const OperationDriverServiceUpdateDriver = "/driver.v1.DriverService/UpdateDriver"
const OperationDriverServiceUpdateVehicle = "/driver.v1.DriverService/UpdateVehicle"

type DriverServiceHTTPServer interface {
	AckMessage(context.Context, *AckMessageRequest) (*AckMessageReply, error)
	DeleteVehicle(context.Context, *DeleteVehicleRequest) (*DeleteVehicleReply, error)
	EnsureDriver(context.Context, *EnsureDriverRequest) (*DriverProfileReply, error)
	GetCertification(context.Context, *GetCertificationRequest) (*CertificationReply, error)
	GetDriver(context.Context, *GetDriverRequest) (*DriverProfileReply, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesReply, error)
	ListVehicles(context.Context, *ListVehiclesRequest) (*ListVehiclesReply, error)
	ReplayDriverTrack(context.Context, *ReplayDriverTrackRequest) (*ReplayDriverTrackReply, error)
	ReportDriverLocation(context.Context, *ReportDriverLocationRequest) (*DriverLocationReply, error)
	SaveVehicle(context.Context, *SaveVehicleRequest) (*VehicleReply, error)
	SubmitCertification(context.Context, *SubmitCertificationRequest) (*CertificationReply, error)
	UpdateDriver(context.Context, *UpdateDriverRequest) (*DriverProfileReply, error)
	UpdateVehicle(context.Context, *UpdateVehicleRequest) (*VehicleReply, error)
}

func RegisterDriverServiceHTTPServer(s *http.Server, srv DriverServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/drivers/ensure", _DriverService_EnsureDriver0_HTTP_Handler(srv))
	r.GET("/v1/drivers/{id}", _DriverService_GetDriver0_HTTP_Handler(srv))
	r.PUT("/v1/drivers/{id}", _DriverService_UpdateDriver0_HTTP_Handler(srv))
	r.POST("/v1/drivers/{id}/certification", _DriverService_SubmitCertification0_HTTP_Handler(srv))
	r.GET("/v1/drivers/{id}/certification", _DriverService_GetCertification0_HTTP_Handler(srv))
	r.POST("/v1/drivers/{id}/vehicles", _DriverService_SaveVehicle0_HTTP_Handler(srv))
	r.PUT("/v1/drivers/{driver_id}/vehicles/{vehicle_id}", _DriverService_UpdateVehicle0_HTTP_Handler(srv))
	r.DELETE("/v1/drivers/{driver_id}/vehicles/{vehicle_id}", _DriverService_DeleteVehicle0_HTTP_Handler(srv))
	r.GET("/v1/drivers/{id}/vehicles", _DriverService_ListVehicles0_HTTP_Handler(srv))
	r.GET("/v1/drivers/{driver_id}/messages", _DriverService_ListMessages0_HTTP_Handler(srv))
	r.POST("/v1/drivers/{driver_id}/messages/{message_id}/ack", _DriverService_AckMessage0_HTTP_Handler(srv))
	r.POST("/v1/drivers/{driver_id}/location/report", _DriverService_ReportDriverLocation0_HTTP_Handler(srv))
	r.GET("/v1/drivers/{driver_id}/track/replay", _DriverService_ReplayDriverTrack0_HTTP_Handler(srv))
}

func _DriverService_EnsureDriver0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnsureDriverRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceEnsureDriver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnsureDriver(ctx, req.(*EnsureDriverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DriverProfileReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_GetDriver0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDriverRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceGetDriver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDriver(ctx, req.(*GetDriverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DriverProfileReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_UpdateDriver0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDriverRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceUpdateDriver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDriver(ctx, req.(*UpdateDriverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DriverProfileReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_SubmitCertification0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitCertificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceSubmitCertification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitCertification(ctx, req.(*SubmitCertificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CertificationReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_GetCertification0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCertificationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceGetCertification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCertification(ctx, req.(*GetCertificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CertificationReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_SaveVehicle0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveVehicleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceSaveVehicle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveVehicle(ctx, req.(*SaveVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VehicleReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_UpdateVehicle0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateVehicleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceUpdateVehicle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateVehicle(ctx, req.(*UpdateVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VehicleReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_DeleteVehicle0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteVehicleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceDeleteVehicle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteVehicle(ctx, req.(*DeleteVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteVehicleReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_ListVehicles0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVehiclesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceListVehicles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVehicles(ctx, req.(*ListVehiclesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVehiclesReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_ListMessages0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMessagesReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_AckMessage0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AckMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceAckMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AckMessage(ctx, req.(*AckMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AckMessageReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_ReportDriverLocation0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReportDriverLocationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceReportDriverLocation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReportDriverLocation(ctx, req.(*ReportDriverLocationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DriverLocationReply)
		return ctx.Result(200, reply)
	}
}

func _DriverService_ReplayDriverTrack0_HTTP_Handler(srv DriverServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReplayDriverTrackRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDriverServiceReplayDriverTrack)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReplayDriverTrack(ctx, req.(*ReplayDriverTrackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReplayDriverTrackReply)
		return ctx.Result(200, reply)
	}
}

type DriverServiceHTTPClient interface {
	AckMessage(ctx context.Context, req *AckMessageRequest, opts ...http.CallOption) (rsp *AckMessageReply, err error)
	DeleteVehicle(ctx context.Context, req *DeleteVehicleRequest, opts ...http.CallOption) (rsp *DeleteVehicleReply, err error)
	EnsureDriver(ctx context.Context, req *EnsureDriverRequest, opts ...http.CallOption) (rsp *DriverProfileReply, err error)
	GetCertification(ctx context.Context, req *GetCertificationRequest, opts ...http.CallOption) (rsp *CertificationReply, err error)
	GetDriver(ctx context.Context, req *GetDriverRequest, opts ...http.CallOption) (rsp *DriverProfileReply, err error)
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *ListMessagesReply, err error)
	ListVehicles(ctx context.Context, req *ListVehiclesRequest, opts ...http.CallOption) (rsp *ListVehiclesReply, err error)
	ReplayDriverTrack(ctx context.Context, req *ReplayDriverTrackRequest, opts ...http.CallOption) (rsp *ReplayDriverTrackReply, err error)
	ReportDriverLocation(ctx context.Context, req *ReportDriverLocationRequest, opts ...http.CallOption) (rsp *DriverLocationReply, err error)
	SaveVehicle(ctx context.Context, req *SaveVehicleRequest, opts ...http.CallOption) (rsp *VehicleReply, err error)
	SubmitCertification(ctx context.Context, req *SubmitCertificationRequest, opts ...http.CallOption) (rsp *CertificationReply, err error)
	UpdateDriver(ctx context.Context, req *UpdateDriverRequest, opts ...http.CallOption) (rsp *DriverProfileReply, err error)
	UpdateVehicle(ctx context.Context, req *UpdateVehicleRequest, opts ...http.CallOption) (rsp *VehicleReply, err error)
}

type DriverServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDriverServiceHTTPClient(client *http.Client) DriverServiceHTTPClient {
	return &DriverServiceHTTPClientImpl{client}
}

func (c *DriverServiceHTTPClientImpl) AckMessage(ctx context.Context, in *AckMessageRequest, opts ...http.CallOption) (*AckMessageReply, error) {
	var out AckMessageReply
	pattern := "/v1/drivers/{driver_id}/messages/{message_id}/ack"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDriverServiceAckMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...http.CallOption) (*DeleteVehicleReply, error) {
	var out DeleteVehicleReply
	pattern := "/v1/drivers/{driver_id}/vehicles/{vehicle_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDriverServiceDeleteVehicle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) EnsureDriver(ctx context.Context, in *EnsureDriverRequest, opts ...http.CallOption) (*DriverProfileReply, error) {
	var out DriverProfileReply
	pattern := "/v1/drivers/ensure"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDriverServiceEnsureDriver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) GetCertification(ctx context.Context, in *GetCertificationRequest, opts ...http.CallOption) (*CertificationReply, error) {
	var out CertificationReply
	pattern := "/v1/drivers/{id}/certification"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDriverServiceGetCertification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) GetDriver(ctx context.Context, in *GetDriverRequest, opts ...http.CallOption) (*DriverProfileReply, error) {
	var out DriverProfileReply
	pattern := "/v1/drivers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDriverServiceGetDriver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*ListMessagesReply, error) {
	var out ListMessagesReply
	pattern := "/v1/drivers/{driver_id}/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDriverServiceListMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...http.CallOption) (*ListVehiclesReply, error) {
	var out ListVehiclesReply
	pattern := "/v1/drivers/{id}/vehicles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDriverServiceListVehicles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) ReplayDriverTrack(ctx context.Context, in *ReplayDriverTrackRequest, opts ...http.CallOption) (*ReplayDriverTrackReply, error) {
	var out ReplayDriverTrackReply
	pattern := "/v1/drivers/{driver_id}/track/replay"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDriverServiceReplayDriverTrack))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) ReportDriverLocation(ctx context.Context, in *ReportDriverLocationRequest, opts ...http.CallOption) (*DriverLocationReply, error) {
	var out DriverLocationReply
	pattern := "/v1/drivers/{driver_id}/location/report"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDriverServiceReportDriverLocation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) SaveVehicle(ctx context.Context, in *SaveVehicleRequest, opts ...http.CallOption) (*VehicleReply, error) {
	var out VehicleReply
	pattern := "/v1/drivers/{id}/vehicles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDriverServiceSaveVehicle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) SubmitCertification(ctx context.Context, in *SubmitCertificationRequest, opts ...http.CallOption) (*CertificationReply, error) {
	var out CertificationReply
	pattern := "/v1/drivers/{id}/certification"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDriverServiceSubmitCertification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) UpdateDriver(ctx context.Context, in *UpdateDriverRequest, opts ...http.CallOption) (*DriverProfileReply, error) {
	var out DriverProfileReply
	pattern := "/v1/drivers/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDriverServiceUpdateDriver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DriverServiceHTTPClientImpl) UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...http.CallOption) (*VehicleReply, error) {
	var out VehicleReply
	pattern := "/v1/drivers/{driver_id}/vehicles/{vehicle_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDriverServiceUpdateVehicle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
