// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/registry"
	"go.uber.org/zap"
	"ride-hailing/services/driver-service/internal/biz"
	"ride-hailing/services/driver-service/internal/conf"
	"ride-hailing/services/driver-service/internal/data"
	"ride-hailing/services/driver-service/internal/server"
	"ride-hailing/services/driver-service/internal/service"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger *zap.Logger, registrar registry.Registrar) (*kratos.App, error) {
	confServer := bootstrap.Server
	node, err := data.NewSnowflakeNode(confServer)
	if err != nil {
		return nil, err
	}
	confData := bootstrap.Data
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, err
	}
	driverRepo := data.NewDriverRepo(db, logger)
	realName := bootstrap.RealName
	verifier := data.NewRealNameVerifier(realName)
	driverUsecase := biz.NewDriverUsecaseWithVerifier(node, logger, driverRepo, verifier)
	driverService := service.NewDriverService(driverUsecase)
	httpServer := server.NewHTTPServer(confServer, driverService)
	grpcServer := server.NewGRPCServer(confServer, driverService)
	app := newApp(httpServer, grpcServer, registrar)
	return app, nil
}
