// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: review/v1/review.proto

package reviewv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	FromUserId    int64                  `protobuf:"varint,5,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewRequest) Reset() {
	*x = SubmitReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewRequest) ProtoMessage() {}

func (x *SubmitReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitReviewRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *SubmitReviewRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SubmitReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *SubmitReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitReviewRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

type SubmitReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewReply) Reset() {
	*x = SubmitReviewReply{}
	mi := &file_review_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewReply) ProtoMessage() {}

func (x *SubmitReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewReply.ProtoReflect.Descriptor instead.
func (*SubmitReviewReply) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitReviewReply) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type ReviewItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewItem) Reset() {
	*x = ReviewItem{}
	mi := &file_review_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewItem) ProtoMessage() {}

func (x *ReviewItem) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewItem.ProtoReflect.Descriptor instead.
func (*ReviewItem) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReviewItem) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *ReviewItem) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ReviewItem) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetMyReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReviewRequest) Reset() {
	*x = GetMyReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReviewRequest) ProtoMessage() {}

func (x *GetMyReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReviewRequest.ProtoReflect.Descriptor instead.
func (*GetMyReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyReviewRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetMyReviewRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

type GetMyReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasReview     bool                   `protobuf:"varint,1,opt,name=has_review,json=hasReview,proto3" json:"has_review,omitempty"`
	Review        *ReviewItem            `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReviewReply) Reset() {
	*x = GetMyReviewReply{}
	mi := &file_review_v1_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReviewReply) ProtoMessage() {}

func (x *GetMyReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReviewReply.ProtoReflect.Descriptor instead.
func (*GetMyReviewReply) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyReviewReply) GetHasReview() bool {
	if x != nil {
		return x.HasReview
	}
	return false
}

func (x *GetMyReviewReply) GetReview() *ReviewItem {
	if x != nil {
		return x.Review
	}
	return nil
}

var File_review_v1_review_proto protoreflect.FileDescriptor

const file_review_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x16review/v1/review.proto\x12\treview.v1\x1a\x1cgoogle/api/annotations.proto\"\xa2\x01\n" +
	"\x13SubmitReviewRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\ffrom_user_id\x18\x05 \x01(\x03R\n" +
	"fromUserId\"0\n" +
	"\x11SubmitReviewReply\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\"\xc8\x01\n" +
	"\n" +
	"ReviewItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\x03R\btoUserId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"Q\n" +
	"\x12GetMyReviewRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\"`\n" +
	"\x10GetMyReviewReply\x12\x1d\n" +
	"\n" +
	"has_review\x18\x01 \x01(\bR\thasReview\x12-\n" +
	"\x06review\x18\x02 \x01(\v2\x15.review.v1.ReviewItemR\x06review2\xe5\x01\n" +
	"\rReviewService\x12d\n" +
	"\fSubmitReview\x12\x1e.review.v1.SubmitReviewRequest\x1a\x1c.review.v1.SubmitReviewReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/reviews\x12n\n" +
	"\vGetMyReview\x12\x1d.review.v1.GetMyReviewRequest\x1a\x1b.review.v1.GetMyReviewReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/reviews/mine/{order_id}B=Z;ride-hailing/services/review-service/api/review/v1;reviewv1b\x06proto3"

var (
	file_review_v1_review_proto_rawDescOnce sync.Once
	file_review_v1_review_proto_rawDescData []byte
)

func file_review_v1_review_proto_rawDescGZIP() []byte {
	file_review_v1_review_proto_rawDescOnce.Do(func() {
		file_review_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)))
	})
	return file_review_v1_review_proto_rawDescData
}

var file_review_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_review_v1_review_proto_goTypes = []any{
	(*SubmitReviewRequest)(nil), // 0: review.v1.SubmitReviewRequest
	(*SubmitReviewReply)(nil),   // 1: review.v1.SubmitReviewReply
	(*ReviewItem)(nil),          // 2: review.v1.ReviewItem
	(*GetMyReviewRequest)(nil),  // 3: review.v1.GetMyReviewRequest
	(*GetMyReviewReply)(nil),    // 4: review.v1.GetMyReviewReply
}
var file_review_v1_review_proto_depIdxs = []int32{
	2, // 0: review.v1.GetMyReviewReply.review:type_name -> review.v1.ReviewItem
	0, // 1: review.v1.ReviewService.SubmitReview:input_type -> review.v1.SubmitReviewRequest
	3, // 2: review.v1.ReviewService.GetMyReview:input_type -> review.v1.GetMyReviewRequest
	1, // 3: review.v1.ReviewService.SubmitReview:output_type -> review.v1.SubmitReviewReply
	4, // 4: review.v1.ReviewService.GetMyReview:output_type -> review.v1.GetMyReviewReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_review_v1_review_proto_init() }
func file_review_v1_review_proto_init() {
	if File_review_v1_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_v1_review_proto_goTypes,
		DependencyIndexes: file_review_v1_review_proto_depIdxs,
		MessageInfos:      file_review_v1_review_proto_msgTypes,
	}.Build()
	File_review_v1_review_proto = out.File
	file_review_v1_review_proto_goTypes = nil
	file_review_v1_review_proto_depIdxs = nil
}
