// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: order/v1/order.proto

package orderv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        int64                  `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	SeatsBooked   int32                  `protobuf:"varint,2,opt,name=seats_booked,json=seatsBooked,proto3" json:"seats_booked,omitempty"`
	PassengerId   int64                  `protobuf:"varint,3,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *CreateOrderRequest) GetSeatsBooked() int32 {
	if x != nil {
		return x.SeatsBooked
	}
	return 0
}

func (x *CreateOrderRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReply) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderReply) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CancelOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PassengerId    int64                  `protobuf:"varint,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancelOrderRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *CancelOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CancelOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReply) Reset() {
	*x = CancelOrderReply{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReply) ProtoMessage() {}

func (x *CancelOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReply.ProtoReflect.Descriptor instead.
func (*CancelOrderReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PassengerId   int64                  `protobuf:"varint,4,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,5,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *ListOrdersRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type GetOrderDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PassengerId   int64                  `protobuf:"varint,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailRequest) Reset() {
	*x = GetOrderDetailRequest{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailRequest) ProtoMessage() {}

func (x *GetOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderDetailRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

type PendingOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        int64                  `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingOrdersRequest) Reset() {
	*x = PendingOrdersRequest{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingOrdersRequest) ProtoMessage() {}

func (x *PendingOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingOrdersRequest.ProtoReflect.Descriptor instead.
func (*PendingOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *PendingOrdersRequest) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *PendingOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PendingOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PendingOrdersRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type AcceptOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId       int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AcceptOrderRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *AcceptOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type AcceptOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderReply) Reset() {
	*x = AcceptOrderReply{}
	mi := &file_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderReply) ProtoMessage() {}

func (x *AcceptOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderReply.ProtoReflect.Descriptor instead.
func (*AcceptOrderReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{8}
}

type RejectOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId       int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RejectReason   string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RejectOrderRequest) Reset() {
	*x = RejectOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectOrderRequest) ProtoMessage() {}

func (x *RejectOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectOrderRequest.ProtoReflect.Descriptor instead.
func (*RejectOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *RejectOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RejectOrderRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *RejectOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RejectOrderRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type RejectOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectOrderReply) Reset() {
	*x = RejectOrderReply{}
	mi := &file_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectOrderReply) ProtoMessage() {}

func (x *RejectOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectOrderReply.ProtoReflect.Descriptor instead.
func (*RejectOrderReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{10}
}

type StartPickupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId       int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartPickupRequest) Reset() {
	*x = StartPickupRequest{}
	mi := &file_order_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPickupRequest) ProtoMessage() {}

func (x *StartPickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPickupRequest.ProtoReflect.Descriptor instead.
func (*StartPickupRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *StartPickupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StartPickupRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *StartPickupRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type StartPickupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPickupReply) Reset() {
	*x = StartPickupReply{}
	mi := &file_order_v1_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPickupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPickupReply) ProtoMessage() {}

func (x *StartPickupReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPickupReply.ProtoReflect.Descriptor instead.
func (*StartPickupReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{12}
}

type StartDeliveryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId       int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartDeliveryRequest) Reset() {
	*x = StartDeliveryRequest{}
	mi := &file_order_v1_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeliveryRequest) ProtoMessage() {}

func (x *StartDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeliveryRequest.ProtoReflect.Descriptor instead.
func (*StartDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{13}
}

func (x *StartDeliveryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StartDeliveryRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *StartDeliveryRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type StartDeliveryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDeliveryReply) Reset() {
	*x = StartDeliveryReply{}
	mi := &file_order_v1_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeliveryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeliveryReply) ProtoMessage() {}

func (x *StartDeliveryReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeliveryReply.ProtoReflect.Descriptor instead.
func (*StartDeliveryReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{14}
}

type CompleteOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId       int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteOrderRequest) Reset() {
	*x = CompleteOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderRequest) ProtoMessage() {}

func (x *CompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*CompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteOrderRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *CompleteOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CompleteOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderReply) Reset() {
	*x = CompleteOrderReply{}
	mi := &file_order_v1_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderReply) ProtoMessage() {}

func (x *CompleteOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderReply.ProtoReflect.Descriptor instead.
func (*CompleteOrderReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{16}
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PassengerId   int64                  `protobuf:"varint,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_order_v1_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{17}
}

func (x *CreatePaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *CreatePaymentRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type CreatePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReply) Reset() {
	*x = CreatePaymentReply{}
	mi := &file_order_v1_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReply) ProtoMessage() {}

func (x *CreatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReply.ProtoReflect.Descriptor instead.
func (*CreatePaymentReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePaymentReply) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreatePaymentReply) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentReply) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *CreatePaymentReply) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CreatePaymentReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MarkPaymentPaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	AlipayTradeNo string                 `protobuf:"bytes,2,opt,name=alipay_trade_no,json=alipayTradeNo,proto3" json:"alipay_trade_no,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TradeStatus   string                 `protobuf:"bytes,5,opt,name=trade_status,json=tradeStatus,proto3" json:"trade_status,omitempty"`
	NotifyPayload string                 `protobuf:"bytes,6,opt,name=notify_payload,json=notifyPayload,proto3" json:"notify_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPaymentPaidRequest) Reset() {
	*x = MarkPaymentPaidRequest{}
	mi := &file_order_v1_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaymentPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaymentPaidRequest) ProtoMessage() {}

func (x *MarkPaymentPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaymentPaidRequest.ProtoReflect.Descriptor instead.
func (*MarkPaymentPaidRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{19}
}

func (x *MarkPaymentPaidRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *MarkPaymentPaidRequest) GetAlipayTradeNo() string {
	if x != nil {
		return x.AlipayTradeNo
	}
	return ""
}

func (x *MarkPaymentPaidRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MarkPaymentPaidRequest) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *MarkPaymentPaidRequest) GetTradeStatus() string {
	if x != nil {
		return x.TradeStatus
	}
	return ""
}

func (x *MarkPaymentPaidRequest) GetNotifyPayload() string {
	if x != nil {
		return x.NotifyPayload
	}
	return ""
}

type MarkPaymentPaidReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Duplicated    bool                   `protobuf:"varint,4,opt,name=duplicated,proto3" json:"duplicated,omitempty"`
	PaymentId     int64                  `protobuf:"varint,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderStatus   int32                  `protobuf:"varint,6,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPaymentPaidReply) Reset() {
	*x = MarkPaymentPaidReply{}
	mi := &file_order_v1_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaymentPaidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaymentPaidReply) ProtoMessage() {}

func (x *MarkPaymentPaidReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaymentPaidReply.ProtoReflect.Descriptor instead.
func (*MarkPaymentPaidReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{20}
}

func (x *MarkPaymentPaidReply) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *MarkPaymentPaidReply) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *MarkPaymentPaidReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MarkPaymentPaidReply) GetDuplicated() bool {
	if x != nil {
		return x.Duplicated
	}
	return false
}

func (x *MarkPaymentPaidReply) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *MarkPaymentPaidReply) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PassengerId   int64                  `protobuf:"varint,3,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_order_v1_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{21}
}

func (x *GetPaymentStatusRequest) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *GetPaymentStatusRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetPaymentStatusRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

type GetPaymentStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	PaymentId     int64                  `protobuf:"varint,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusReply) Reset() {
	*x = GetPaymentStatusReply{}
	mi := &file_order_v1_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusReply) ProtoMessage() {}

func (x *GetPaymentStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusReply.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{22}
}

func (x *GetPaymentStatusReply) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetPaymentStatusReply) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *GetPaymentStatusReply) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *GetPaymentStatusReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPaymentStatusReply) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TripId        int64                  `protobuf:"varint,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	PassengerId   int64                  `protobuf:"varint,3,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartTime    string                 `protobuf:"bytes,7,opt,name=depart_time,json=departTime,proto3" json:"depart_time,omitempty"`
	SeatsBooked   int32                  `protobuf:"varint,8,opt,name=seats_booked,json=seatsBooked,proto3" json:"seats_booked,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AcceptedAt    string                 `protobuf:"bytes,12,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	RejectReason  string                 `protobuf:"bytes,13,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	RejectedAt    string                 `protobuf:"bytes,14,opt,name=rejected_at,json=rejectedAt,proto3" json:"rejected_at,omitempty"`
	RefundAmount  float64                `protobuf:"fixed64,15,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	RefundedAt    string                 `protobuf:"bytes,16,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_v1_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{23}
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *OrderItem) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *OrderItem) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *OrderItem) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *OrderItem) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *OrderItem) GetDepartTime() string {
	if x != nil {
		return x.DepartTime
	}
	return ""
}

func (x *OrderItem) GetSeatsBooked() int32 {
	if x != nil {
		return x.SeatsBooked
	}
	return 0
}

func (x *OrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderItem) GetAcceptedAt() string {
	if x != nil {
		return x.AcceptedAt
	}
	return ""
}

func (x *OrderItem) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *OrderItem) GetRejectedAt() string {
	if x != nil {
		return x.RejectedAt
	}
	return ""
}

func (x *OrderItem) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *OrderItem) GetRefundedAt() string {
	if x != nil {
		return x.RefundedAt
	}
	return ""
}

type ListOrdersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReply) Reset() {
	*x = ListOrdersReply{}
	mi := &file_order_v1_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReply) ProtoMessage() {}

func (x *ListOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReply.ProtoReflect.Descriptor instead.
func (*ListOrdersReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{24}
}

func (x *ListOrdersReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersReply) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOrderDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderItem             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailReply) Reset() {
	*x = GetOrderDetailReply{}
	mi := &file_order_v1_order_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReply) ProtoMessage() {}

func (x *GetOrderDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReply.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{25}
}

func (x *GetOrderDetailReply) GetOrder() *OrderItem {
	if x != nil {
		return x.Order
	}
	return nil
}

type PendingOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TripId        int64                  `protobuf:"varint,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	PassengerId   int64                  `protobuf:"varint,3,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	SeatsBooked   int32                  `protobuf:"varint,4,opt,name=seats_booked,json=seatsBooked,proto3" json:"seats_booked,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingOrderItem) Reset() {
	*x = PendingOrderItem{}
	mi := &file_order_v1_order_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingOrderItem) ProtoMessage() {}

func (x *PendingOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingOrderItem.ProtoReflect.Descriptor instead.
func (*PendingOrderItem) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{26}
}

func (x *PendingOrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PendingOrderItem) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *PendingOrderItem) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *PendingOrderItem) GetSeatsBooked() int32 {
	if x != nil {
		return x.SeatsBooked
	}
	return 0
}

func (x *PendingOrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *PendingOrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PendingOrderItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PendingOrdersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*PendingOrderItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingOrdersReply) Reset() {
	*x = PendingOrdersReply{}
	mi := &file_order_v1_order_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingOrdersReply) ProtoMessage() {}

func (x *PendingOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingOrdersReply.ProtoReflect.Descriptor instead.
func (*PendingOrdersReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{27}
}

func (x *PendingOrdersReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PendingOrdersReply) GetItems() []*PendingOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DriverIncomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverIncomeRequest) Reset() {
	*x = DriverIncomeRequest{}
	mi := &file_order_v1_order_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverIncomeRequest) ProtoMessage() {}

func (x *DriverIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverIncomeRequest.ProtoReflect.Descriptor instead.
func (*DriverIncomeRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{28}
}

func (x *DriverIncomeRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverIncomeRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *DriverIncomeRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *DriverIncomeRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DriverIncomeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DriverIncomeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PassengerId   int64                  `protobuf:"varint,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	TripId        int64                  `protobuf:"varint,3,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	AcceptedAt    string                 `protobuf:"bytes,8,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverIncomeRecord) Reset() {
	*x = DriverIncomeRecord{}
	mi := &file_order_v1_order_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverIncomeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverIncomeRecord) ProtoMessage() {}

func (x *DriverIncomeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverIncomeRecord.ProtoReflect.Descriptor instead.
func (*DriverIncomeRecord) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{29}
}

func (x *DriverIncomeRecord) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DriverIncomeRecord) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *DriverIncomeRecord) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *DriverIncomeRecord) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *DriverIncomeRecord) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *DriverIncomeRecord) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DriverIncomeRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DriverIncomeRecord) GetAcceptedAt() string {
	if x != nil {
		return x.AcceptedAt
	}
	return ""
}

type DriverIncomeReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TodayOrders     int64                  `protobuf:"varint,1,opt,name=today_orders,json=todayOrders,proto3" json:"today_orders,omitempty"`
	TodayIncome     float64                `protobuf:"fixed64,2,opt,name=today_income,json=todayIncome,proto3" json:"today_income,omitempty"`
	PendingWithdraw float64                `protobuf:"fixed64,3,opt,name=pending_withdraw,json=pendingWithdraw,proto3" json:"pending_withdraw,omitempty"`
	Records         []*DriverIncomeRecord  `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DriverIncomeReply) Reset() {
	*x = DriverIncomeReply{}
	mi := &file_order_v1_order_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverIncomeReply) ProtoMessage() {}

func (x *DriverIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverIncomeReply.ProtoReflect.Descriptor instead.
func (*DriverIncomeReply) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{30}
}

func (x *DriverIncomeReply) GetTodayOrders() int64 {
	if x != nil {
		return x.TodayOrders
	}
	return 0
}

func (x *DriverIncomeReply) GetTodayIncome() float64 {
	if x != nil {
		return x.TodayIncome
	}
	return 0
}

func (x *DriverIncomeReply) GetPendingWithdraw() float64 {
	if x != nil {
		return x.PendingWithdraw
	}
	return 0
}

func (x *DriverIncomeReply) GetRecords() []*DriverIncomeRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\"s\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\x03R\x06tripId\x12!\n" +
	"\fseats_booked\x18\x02 \x01(\x05R\vseatsBooked\x12!\n" +
	"\fpassenger_id\x18\x03 \x01(\x03R\vpassengerId\"N\n" +
	"\x10CreateOrderReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x01R\n" +
	"totalPrice\"p\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\x03R\vpassengerId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x12\n" +
	"\x10CancelOrderReply\"\x9c\x01\n" +
	"\x11ListOrdersRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12!\n" +
	"\fpassenger_id\x18\x04 \x01(\x03R\vpassengerId\x12\x1b\n" +
	"\tdriver_id\x18\x05 \x01(\x03R\bdriverId\"J\n" +
	"\x15GetOrderDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\x03R\vpassengerId\"}\n" +
	"\x14PendingOrdersRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\x03R\x06tripId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\"j\n" +
	"\x12AcceptOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x12\n" +
	"\x10AcceptOrderReply\"\x8f\x01\n" +
	"\x12RejectOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\"\x12\n" +
	"\x10RejectOrderReply\"j\n" +
	"\x12StartPickupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x12\n" +
	"\x10StartPickupReply\"l\n" +
	"\x14StartDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x14\n" +
	"\x12StartDeliveryReply\"l\n" +
	"\x14CompleteOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x14\n" +
	"\x12CompleteOrderReply\"n\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\x03R\vpassengerId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"\xab\x01\n" +
	"\x12CreatePaymentReply\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12 \n" +
	"\fout_trade_no\x18\x03 \x01(\tR\n" +
	"outTradeNo\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xe6\x01\n" +
	"\x16MarkPaymentPaidRequest\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12&\n" +
	"\x0falipay_trade_no\x18\x02 \x01(\tR\ralipayTradeNo\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\tR\vtotalAmount\x12!\n" +
	"\ftrade_status\x18\x05 \x01(\tR\vtradeStatus\x12%\n" +
	"\x0enotify_payload\x18\x06 \x01(\tR\rnotifyPayload\"\xcd\x01\n" +
	"\x14MarkPaymentPaidReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12 \n" +
	"\fout_trade_no\x18\x02 \x01(\tR\n" +
	"outTradeNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"duplicated\x18\x04 \x01(\bR\n" +
	"duplicated\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x05 \x01(\x03R\tpaymentId\x12!\n" +
	"\forder_status\x18\x06 \x01(\x05R\vorderStatus\"y\n" +
	"\x17GetPaymentStatusRequest\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12!\n" +
	"\fpassenger_id\x18\x03 \x01(\x03R\vpassengerId\"\xae\x01\n" +
	"\x15GetPaymentStatusReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12 \n" +
	"\fout_trade_no\x18\x02 \x01(\tR\n" +
	"outTradeNo\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x05 \x01(\x03R\tpaymentId\"\xf7\x03\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\x03R\x06tripId\x12!\n" +
	"\fpassenger_id\x18\x03 \x01(\x03R\vpassengerId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x03R\bdriverId\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x06 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdepart_time\x18\a \x01(\tR\n" +
	"departTime\x12!\n" +
	"\fseats_booked\x18\b \x01(\x05R\vseatsBooked\x12\x1f\n" +
	"\vtotal_price\x18\t \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vaccepted_at\x18\f \x01(\tR\n" +
	"acceptedAt\x12#\n" +
	"\rreject_reason\x18\r \x01(\tR\frejectReason\x12\x1f\n" +
	"\vrejected_at\x18\x0e \x01(\tR\n" +
	"rejectedAt\x12#\n" +
	"\rrefund_amount\x18\x0f \x01(\x01R\frefundAmount\x12\x1f\n" +
	"\vrefunded_at\x18\x10 \x01(\tR\n" +
	"refundedAt\"R\n" +
	"\x0fListOrdersReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.order.v1.OrderItemR\x05items\"@\n" +
	"\x13GetOrderDetailReply\x12)\n" +
	"\x05order\x18\x01 \x01(\v2\x13.order.v1.OrderItemR\x05order\"\xd9\x01\n" +
	"\x10PendingOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\x03R\x06tripId\x12!\n" +
	"\fpassenger_id\x18\x03 \x01(\x03R\vpassengerId\x12!\n" +
	"\fseats_booked\x18\x04 \x01(\x05R\vseatsBooked\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\\\n" +
	"\x12PendingOrdersReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.order.v1.PendingOrderItemR\x05items\"\x9d\x01\n" +
	"\x13DriverIncomeRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xf6\x01\n" +
	"\x12DriverIncomeRecord\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\x03R\vpassengerId\x12\x17\n" +
	"\atrip_id\x18\x03 \x01(\x03R\x06tripId\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1f\n" +
	"\vaccepted_at\x18\b \x01(\tR\n" +
	"acceptedAt\"\xbc\x01\n" +
	"\x11DriverIncomeReply\x12!\n" +
	"\ftoday_orders\x18\x01 \x01(\x03R\vtodayOrders\x12!\n" +
	"\ftoday_income\x18\x02 \x01(\x01R\vtodayIncome\x12)\n" +
	"\x10pending_withdraw\x18\x03 \x01(\x01R\x0fpendingWithdraw\x126\n" +
	"\arecords\x18\x04 \x03(\v2\x1c.order.v1.DriverIncomeRecordR\arecords2\xa6\f\n" +
	"\fOrderService\x12^\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1a.order.v1.CreateOrderReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12j\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x1a.order.v1.CancelOrderReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/orders/{id}/cancel\x12X\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x19.order.v1.ListOrdersReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12i\n" +
	"\x0eGetOrderDetail\x12\x1f.order.v1.GetOrderDetailRequest\x1a\x1d.order.v1.GetOrderDetailReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/orders/{id}\x12p\n" +
	"\rPendingOrders\x12\x1e.order.v1.PendingOrdersRequest\x1a\x1c.order.v1.PendingOrdersReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/driver/orders/pending\x12q\n" +
	"\vAcceptOrder\x12\x1c.order.v1.AcceptOrderRequest\x1a\x1a.order.v1.AcceptOrderReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/driver/orders/{id}/accept\x12q\n" +
	"\vRejectOrder\x12\x1c.order.v1.RejectOrderRequest\x1a\x1a.order.v1.RejectOrderReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/driver/orders/{id}/reject\x12w\n" +
	"\vStartPickup\x12\x1c.order.v1.StartPickupRequest\x1a\x1a.order.v1.StartPickupReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/driver/orders/{id}/start-pickup\x12\x7f\n" +
	"\rStartDelivery\x12\x1e.order.v1.StartDeliveryRequest\x1a\x1c.order.v1.StartDeliveryReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/driver/orders/{id}/start-delivery\x12y\n" +
	"\rCompleteOrder\x12\x1e.order.v1.CompleteOrderRequest\x1a\x1c.order.v1.CompleteOrderReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/driver/orders/{id}/complete\x12f\n" +
	"\rCreatePayment\x12\x1e.order.v1.CreatePaymentRequest\x1a\x1c.order.v1.CreatePaymentReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/payments\x12q\n" +
	"\x0fMarkPaymentPaid\x12 .order.v1.MarkPaymentPaidRequest\x1a\x1e.order.v1.MarkPaymentPaidReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/payments/paid\x12s\n" +
	"\x10GetPaymentStatus\x12!.order.v1.GetPaymentStatusRequest\x1a\x1f.order.v1.GetPaymentStatusReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/payments/status\x12h\n" +
	"\x0fGetDriverIncome\x12\x1d.order.v1.DriverIncomeRequest\x1a\x1b.order.v1.DriverIncomeReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/driver/incomeB:Z8ride-hailing/services/order-service/api/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_order_v1_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),      // 0: order.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),        // 1: order.v1.CreateOrderReply
	(*CancelOrderRequest)(nil),      // 2: order.v1.CancelOrderRequest
	(*CancelOrderReply)(nil),        // 3: order.v1.CancelOrderReply
	(*ListOrdersRequest)(nil),       // 4: order.v1.ListOrdersRequest
	(*GetOrderDetailRequest)(nil),   // 5: order.v1.GetOrderDetailRequest
	(*PendingOrdersRequest)(nil),    // 6: order.v1.PendingOrdersRequest
	(*AcceptOrderRequest)(nil),      // 7: order.v1.AcceptOrderRequest
	(*AcceptOrderReply)(nil),        // 8: order.v1.AcceptOrderReply
	(*RejectOrderRequest)(nil),      // 9: order.v1.RejectOrderRequest
	(*RejectOrderReply)(nil),        // 10: order.v1.RejectOrderReply
	(*StartPickupRequest)(nil),      // 11: order.v1.StartPickupRequest
	(*StartPickupReply)(nil),        // 12: order.v1.StartPickupReply
	(*StartDeliveryRequest)(nil),    // 13: order.v1.StartDeliveryRequest
	(*StartDeliveryReply)(nil),      // 14: order.v1.StartDeliveryReply
	(*CompleteOrderRequest)(nil),    // 15: order.v1.CompleteOrderRequest
	(*CompleteOrderReply)(nil),      // 16: order.v1.CompleteOrderReply
	(*CreatePaymentRequest)(nil),    // 17: order.v1.CreatePaymentRequest
	(*CreatePaymentReply)(nil),      // 18: order.v1.CreatePaymentReply
	(*MarkPaymentPaidRequest)(nil),  // 19: order.v1.MarkPaymentPaidRequest
	(*MarkPaymentPaidReply)(nil),    // 20: order.v1.MarkPaymentPaidReply
	(*GetPaymentStatusRequest)(nil), // 21: order.v1.GetPaymentStatusRequest
	(*GetPaymentStatusReply)(nil),   // 22: order.v1.GetPaymentStatusReply
	(*OrderItem)(nil),               // 23: order.v1.OrderItem
	(*ListOrdersReply)(nil),         // 24: order.v1.ListOrdersReply
	(*GetOrderDetailReply)(nil),     // 25: order.v1.GetOrderDetailReply
	(*PendingOrderItem)(nil),        // 26: order.v1.PendingOrderItem
	(*PendingOrdersReply)(nil),      // 27: order.v1.PendingOrdersReply
	(*DriverIncomeRequest)(nil),     // 28: order.v1.DriverIncomeRequest
	(*DriverIncomeRecord)(nil),      // 29: order.v1.DriverIncomeRecord
	(*DriverIncomeReply)(nil),       // 30: order.v1.DriverIncomeReply
}
var file_order_v1_order_proto_depIdxs = []int32{
	23, // 0: order.v1.ListOrdersReply.items:type_name -> order.v1.OrderItem
	23, // 1: order.v1.GetOrderDetailReply.order:type_name -> order.v1.OrderItem
	26, // 2: order.v1.PendingOrdersReply.items:type_name -> order.v1.PendingOrderItem
	29, // 3: order.v1.DriverIncomeReply.records:type_name -> order.v1.DriverIncomeRecord
	0,  // 4: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	2,  // 5: order.v1.OrderService.CancelOrder:input_type -> order.v1.CancelOrderRequest
	4,  // 6: order.v1.OrderService.ListOrders:input_type -> order.v1.ListOrdersRequest
	5,  // 7: order.v1.OrderService.GetOrderDetail:input_type -> order.v1.GetOrderDetailRequest
	6,  // 8: order.v1.OrderService.PendingOrders:input_type -> order.v1.PendingOrdersRequest
	7,  // 9: order.v1.OrderService.AcceptOrder:input_type -> order.v1.AcceptOrderRequest
	9,  // 10: order.v1.OrderService.RejectOrder:input_type -> order.v1.RejectOrderRequest
	11, // 11: order.v1.OrderService.StartPickup:input_type -> order.v1.StartPickupRequest
	13, // 12: order.v1.OrderService.StartDelivery:input_type -> order.v1.StartDeliveryRequest
	15, // 13: order.v1.OrderService.CompleteOrder:input_type -> order.v1.CompleteOrderRequest
	17, // 14: order.v1.OrderService.CreatePayment:input_type -> order.v1.CreatePaymentRequest
	19, // 15: order.v1.OrderService.MarkPaymentPaid:input_type -> order.v1.MarkPaymentPaidRequest
	21, // 16: order.v1.OrderService.GetPaymentStatus:input_type -> order.v1.GetPaymentStatusRequest
	28, // 17: order.v1.OrderService.GetDriverIncome:input_type -> order.v1.DriverIncomeRequest
	1,  // 18: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderReply
	3,  // 19: order.v1.OrderService.CancelOrder:output_type -> order.v1.CancelOrderReply
	24, // 20: order.v1.OrderService.ListOrders:output_type -> order.v1.ListOrdersReply
	25, // 21: order.v1.OrderService.GetOrderDetail:output_type -> order.v1.GetOrderDetailReply
	27, // 22: order.v1.OrderService.PendingOrders:output_type -> order.v1.PendingOrdersReply
	8,  // 23: order.v1.OrderService.AcceptOrder:output_type -> order.v1.AcceptOrderReply
	10, // 24: order.v1.OrderService.RejectOrder:output_type -> order.v1.RejectOrderReply
	12, // 25: order.v1.OrderService.StartPickup:output_type -> order.v1.StartPickupReply
	14, // 26: order.v1.OrderService.StartDelivery:output_type -> order.v1.StartDeliveryReply
	16, // 27: order.v1.OrderService.CompleteOrder:output_type -> order.v1.CompleteOrderReply
	18, // 28: order.v1.OrderService.CreatePayment:output_type -> order.v1.CreatePaymentReply
	20, // 29: order.v1.OrderService.MarkPaymentPaid:output_type -> order.v1.MarkPaymentPaidReply
	22, // 30: order.v1.OrderService.GetPaymentStatus:output_type -> order.v1.GetPaymentStatusReply
	30, // 31: order.v1.OrderService.GetDriverIncome:output_type -> order.v1.DriverIncomeReply
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
