// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: order/v1/order.proto

package orderv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrderServiceAcceptOrder = "/order.v1.OrderService/AcceptOrder"
const OperationOrderServiceCancelOrder = "/order.v1.OrderService/CancelOrder"
const OperationOrderServiceCompleteOrder = "/order.v1.OrderService/CompleteOrder"
const OperationOrderServiceCreateOrder = "/order.v1.OrderService/CreateOrder"
const OperationOrderServiceCreatePayment = "/order.v1.OrderService/CreatePayment"
const OperationOrderServiceGetDriverIncome = "/order.v1.OrderService/GetDriverIncome"
const OperationOrderServiceGetOrderDetail = "/order.v1.OrderService/GetOrderDetail"
const OperationOrderServiceGetPaymentStatus = "/order.v1.OrderService/GetPaymentStatus"
const OperationOrderServiceListOrders = "/order.v1.OrderService/ListOrders"
const OperationOrderServiceMarkPaymentPaid = "/order.v1.OrderService/MarkPaymentPaid"
const OperationOrderServicePendingOrders = "/order.v1.OrderService/PendingOrders"
const OperationOrderServiceRejectOrder = "/order.v1.OrderService/RejectOrder"
const OperationOrderServiceStartDelivery = "/order.v1.OrderService/StartDelivery"
const OperationOrderServiceStartPickup = "/order.v1.OrderService/StartPickup"

type OrderServiceHTTPServer interface {
	AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderReply, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderReply, error)
	CompleteOrder(context.Context, *CompleteOrderRequest) (*CompleteOrderReply, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentReply, error)
	GetDriverIncome(context.Context, *DriverIncomeRequest) (*DriverIncomeReply, error)
	GetOrderDetail(context.Context, *GetOrderDetailRequest) (*GetOrderDetailReply, error)
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*GetPaymentStatusReply, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersReply, error)
	MarkPaymentPaid(context.Context, *MarkPaymentPaidRequest) (*MarkPaymentPaidReply, error)
	PendingOrders(context.Context, *PendingOrdersRequest) (*PendingOrdersReply, error)
	RejectOrder(context.Context, *RejectOrderRequest) (*RejectOrderReply, error)
	StartDelivery(context.Context, *StartDeliveryRequest) (*StartDeliveryReply, error)
	StartPickup(context.Context, *StartPickupRequest) (*StartPickupReply, error)
}

func RegisterOrderServiceHTTPServer(s *http.Server, srv OrderServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/orders", _OrderService_CreateOrder0_HTTP_Handler(srv))
	r.POST("/v1/orders/{id}/cancel", _OrderService_CancelOrder0_HTTP_Handler(srv))
	r.GET("/v1/orders", _OrderService_ListOrders0_HTTP_Handler(srv))
	r.GET("/v1/orders/{id}", _OrderService_GetOrderDetail0_HTTP_Handler(srv))
	r.GET("/v1/driver/orders/pending", _OrderService_PendingOrders0_HTTP_Handler(srv))
	r.POST("/v1/driver/orders/{id}/accept", _OrderService_AcceptOrder0_HTTP_Handler(srv))
	r.POST("/v1/driver/orders/{id}/reject", _OrderService_RejectOrder0_HTTP_Handler(srv))
	r.POST("/v1/driver/orders/{id}/start-pickup", _OrderService_StartPickup0_HTTP_Handler(srv))
	r.POST("/v1/driver/orders/{id}/start-delivery", _OrderService_StartDelivery0_HTTP_Handler(srv))
	r.POST("/v1/driver/orders/{id}/complete", _OrderService_CompleteOrder0_HTTP_Handler(srv))
	r.POST("/v1/payments", _OrderService_CreatePayment0_HTTP_Handler(srv))
	r.POST("/v1/payments/paid", _OrderService_MarkPaymentPaid0_HTTP_Handler(srv))
	r.GET("/v1/payments/status", _OrderService_GetPaymentStatus0_HTTP_Handler(srv))
	r.GET("/v1/driver/income", _OrderService_GetDriverIncome0_HTTP_Handler(srv))
}

func _OrderService_CreateOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCreateOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateOrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_CancelOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCancelOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelOrder(ctx, req.(*CancelOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelOrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ListOrders0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceListOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrders(ctx, req.(*ListOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_GetOrderDetail0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetOrderDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderDetail(ctx, req.(*GetOrderDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderDetailReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_PendingOrders0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PendingOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServicePendingOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PendingOrders(ctx, req.(*PendingOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PendingOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_AcceptOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AcceptOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceAcceptOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AcceptOrder(ctx, req.(*AcceptOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AcceptOrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_RejectOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RejectOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceRejectOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RejectOrder(ctx, req.(*RejectOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RejectOrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_StartPickup0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartPickupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceStartPickup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartPickup(ctx, req.(*StartPickupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartPickupReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_StartDelivery0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartDeliveryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceStartDelivery)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartDelivery(ctx, req.(*StartDeliveryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartDeliveryReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_CompleteOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCompleteOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteOrder(ctx, req.(*CompleteOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompleteOrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_CreatePayment0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePaymentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCreatePayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePayment(ctx, req.(*CreatePaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePaymentReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_MarkPaymentPaid0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkPaymentPaidRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceMarkPaymentPaid)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkPaymentPaid(ctx, req.(*MarkPaymentPaidRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MarkPaymentPaidReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_GetPaymentStatus0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaymentStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetPaymentStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPaymentStatus(ctx, req.(*GetPaymentStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPaymentStatusReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_GetDriverIncome0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DriverIncomeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetDriverIncome)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDriverIncome(ctx, req.(*DriverIncomeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DriverIncomeReply)
		return ctx.Result(200, reply)
	}
}

type OrderServiceHTTPClient interface {
	AcceptOrder(ctx context.Context, req *AcceptOrderRequest, opts ...http.CallOption) (rsp *AcceptOrderReply, err error)
	CancelOrder(ctx context.Context, req *CancelOrderRequest, opts ...http.CallOption) (rsp *CancelOrderReply, err error)
	CompleteOrder(ctx context.Context, req *CompleteOrderRequest, opts ...http.CallOption) (rsp *CompleteOrderReply, err error)
	CreateOrder(ctx context.Context, req *CreateOrderRequest, opts ...http.CallOption) (rsp *CreateOrderReply, err error)
	CreatePayment(ctx context.Context, req *CreatePaymentRequest, opts ...http.CallOption) (rsp *CreatePaymentReply, err error)
	GetDriverIncome(ctx context.Context, req *DriverIncomeRequest, opts ...http.CallOption) (rsp *DriverIncomeReply, err error)
	GetOrderDetail(ctx context.Context, req *GetOrderDetailRequest, opts ...http.CallOption) (rsp *GetOrderDetailReply, err error)
	GetPaymentStatus(ctx context.Context, req *GetPaymentStatusRequest, opts ...http.CallOption) (rsp *GetPaymentStatusReply, err error)
	ListOrders(ctx context.Context, req *ListOrdersRequest, opts ...http.CallOption) (rsp *ListOrdersReply, err error)
	MarkPaymentPaid(ctx context.Context, req *MarkPaymentPaidRequest, opts ...http.CallOption) (rsp *MarkPaymentPaidReply, err error)
	PendingOrders(ctx context.Context, req *PendingOrdersRequest, opts ...http.CallOption) (rsp *PendingOrdersReply, err error)
	RejectOrder(ctx context.Context, req *RejectOrderRequest, opts ...http.CallOption) (rsp *RejectOrderReply, err error)
	StartDelivery(ctx context.Context, req *StartDeliveryRequest, opts ...http.CallOption) (rsp *StartDeliveryReply, err error)
	StartPickup(ctx context.Context, req *StartPickupRequest, opts ...http.CallOption) (rsp *StartPickupReply, err error)
}

type OrderServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderServiceHTTPClient(client *http.Client) OrderServiceHTTPClient {
	return &OrderServiceHTTPClientImpl{client}
}

func (c *OrderServiceHTTPClientImpl) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...http.CallOption) (*AcceptOrderReply, error) {
	var out AcceptOrderReply
	pattern := "/v1/driver/orders/{id}/accept"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceAcceptOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...http.CallOption) (*CancelOrderReply, error) {
	var out CancelOrderReply
	pattern := "/v1/orders/{id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceCancelOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...http.CallOption) (*CompleteOrderReply, error) {
	var out CompleteOrderReply
	pattern := "/v1/driver/orders/{id}/complete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceCompleteOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...http.CallOption) (*CreateOrderReply, error) {
	var out CreateOrderReply
	pattern := "/v1/orders"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceCreateOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...http.CallOption) (*CreatePaymentReply, error) {
	var out CreatePaymentReply
	pattern := "/v1/payments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceCreatePayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) GetDriverIncome(ctx context.Context, in *DriverIncomeRequest, opts ...http.CallOption) (*DriverIncomeReply, error) {
	var out DriverIncomeReply
	pattern := "/v1/driver/income"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceGetDriverIncome))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) GetOrderDetail(ctx context.Context, in *GetOrderDetailRequest, opts ...http.CallOption) (*GetOrderDetailReply, error) {
	var out GetOrderDetailReply
	pattern := "/v1/orders/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceGetOrderDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...http.CallOption) (*GetPaymentStatusReply, error) {
	var out GetPaymentStatusReply
	pattern := "/v1/payments/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceGetPaymentStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...http.CallOption) (*ListOrdersReply, error) {
	var out ListOrdersReply
	pattern := "/v1/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceListOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) MarkPaymentPaid(ctx context.Context, in *MarkPaymentPaidRequest, opts ...http.CallOption) (*MarkPaymentPaidReply, error) {
	var out MarkPaymentPaidReply
	pattern := "/v1/payments/paid"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceMarkPaymentPaid))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) PendingOrders(ctx context.Context, in *PendingOrdersRequest, opts ...http.CallOption) (*PendingOrdersReply, error) {
	var out PendingOrdersReply
	pattern := "/v1/driver/orders/pending"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServicePendingOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) RejectOrder(ctx context.Context, in *RejectOrderRequest, opts ...http.CallOption) (*RejectOrderReply, error) {
	var out RejectOrderReply
	pattern := "/v1/driver/orders/{id}/reject"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceRejectOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) StartDelivery(ctx context.Context, in *StartDeliveryRequest, opts ...http.CallOption) (*StartDeliveryReply, error) {
	var out StartDeliveryReply
	pattern := "/v1/driver/orders/{id}/start-delivery"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceStartDelivery))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) StartPickup(ctx context.Context, in *StartPickupRequest, opts ...http.CallOption) (*StartPickupReply, error) {
	var out StartPickupReply
	pattern := "/v1/driver/orders/{id}/start-pickup"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceStartPickup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
